/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMULTILIGHTGROUPFIELDS_H_
#define _OSGMULTILIGHTGROUPFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MultiLightGroup;

OSG_GEN_CONTAINERPTR(MultiLightGroup);
/*! \ingroup GrpSystemFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<MultiLightGroup *, nsOSG> :
    public FieldTraitsFCPtrBase<MultiLightGroup *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MultiLightGroup *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMultiLightGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightGroup *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMultiLightGroupPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiLightGroup *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMultiLightGroupPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiLightGroup *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMultiLightGroupPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiLightGroup *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMultiLightGroupPtr;
/*! \ingroup GrpSystemFieldSFields */
typedef PointerSField<MultiLightGroup *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMultiLightGroupPtr;


/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiLightGroup *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMultiLightGroupPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiLightGroup *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMultiLightGroupPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiLightGroup *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMultiLightGroupPtr;
/*! \ingroup GrpSystemFieldMFields */
typedef PointerMField<MultiLightGroup *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMultiLightGroupPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecMultiLightGroupPtr : 
    public PointerSField<MultiLightGroup *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecMultiLightGroupPtr : 
    public PointerSField<MultiLightGroup *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakMultiLightGroupPtr :
    public PointerSField<MultiLightGroup *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedMultiLightGroupPtr :
    public PointerSField<MultiLightGroup *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecMultiLightGroupPtr :
    public PointerMField<MultiLightGroup *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecMultiLightGroupPtr :
    public PointerMField<MultiLightGroup *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakMultiLightGroupPtr :
    public PointerMField<MultiLightGroup *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedMultiLightGroupPtr :
    public PointerMField<MultiLightGroup *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMULTILIGHTGROUPFIELDS_H_ */
