/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGIBLSTAGEFIELDS_H_
#define _OSGIBLSTAGEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class IBLStage;

OSG_GEN_CONTAINERPTR(IBLStage);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<IBLStage *, nsOSG> :
    public FieldTraitsFCPtrBase<IBLStage *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<IBLStage *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakIBLStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<IBLStage *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdIBLStagePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<IBLStage *,
                      RecordedRefCountPolicy, nsOSG  > SFRecIBLStagePtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<IBLStage *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecIBLStagePtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<IBLStage *,
                      WeakRefCountPolicy, nsOSG      > SFWeakIBLStagePtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<IBLStage *,
                      NoRefCountPolicy, nsOSG        > SFUncountedIBLStagePtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<IBLStage *,
                      RecordedRefCountPolicy, nsOSG  > MFRecIBLStagePtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<IBLStage *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecIBLStagePtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<IBLStage *,
                      WeakRefCountPolicy, nsOSG      > MFWeakIBLStagePtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<IBLStage *,
                      NoRefCountPolicy, nsOSG        > MFUncountedIBLStagePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecIBLStagePtr : 
    public PointerSField<IBLStage *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecIBLStagePtr : 
    public PointerSField<IBLStage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakIBLStagePtr :
    public PointerSField<IBLStage *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedIBLStagePtr :
    public PointerSField<IBLStage *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecIBLStagePtr :
    public PointerMField<IBLStage *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecIBLStagePtr :
    public PointerMField<IBLStage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakIBLStagePtr :
    public PointerMField<IBLStage *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedIBLStagePtr :
    public PointerMField<IBLStage *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGIBLSTAGEFIELDS_H_ */
