/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERDESCFIELDS_H_
#define _OSGSHADERDESCFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ShaderDesc;

OSG_GEN_CONTAINERPTR(ShaderDesc);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<ShaderDesc *, nsOSG> :
    public FieldTraitsFCPtrBase<ShaderDesc *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ShaderDesc *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderDesc *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderDescPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderDesc *,
                      RecordedRefCountPolicy, nsOSG  > SFRecShaderDescPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderDesc *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecShaderDescPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderDesc *,
                      WeakRefCountPolicy, nsOSG      > SFWeakShaderDescPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderDesc *,
                      NoRefCountPolicy, nsOSG        > SFUncountedShaderDescPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderDesc *,
                      RecordedRefCountPolicy, nsOSG  > MFRecShaderDescPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderDesc *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecShaderDescPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderDesc *,
                      WeakRefCountPolicy, nsOSG      > MFWeakShaderDescPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderDesc *,
                      NoRefCountPolicy, nsOSG        > MFUncountedShaderDescPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecShaderDescPtr : 
    public PointerSField<ShaderDesc *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecShaderDescPtr : 
    public PointerSField<ShaderDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakShaderDescPtr :
    public PointerSField<ShaderDesc *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedShaderDescPtr :
    public PointerSField<ShaderDesc *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecShaderDescPtr :
    public PointerMField<ShaderDesc *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecShaderDescPtr :
    public PointerMField<ShaderDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakShaderDescPtr :
    public PointerMField<ShaderDesc *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedShaderDescPtr :
    public PointerMField<ShaderDesc *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSHADERDESCFIELDS_H_ */
