/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSHADERMANAGERFIELDS_H_
#define _OSGSHADERMANAGERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class ShaderManager;

OSG_GEN_CONTAINERPTR(ShaderManager);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<ShaderManager *, nsOSG> :
    public FieldTraitsFCPtrBase<ShaderManager *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<ShaderManager *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakShaderManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<ShaderManager *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdShaderManagerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderManager *,
                      RecordedRefCountPolicy, nsOSG  > SFRecShaderManagerPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderManager *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecShaderManagerPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderManager *,
                      WeakRefCountPolicy, nsOSG      > SFWeakShaderManagerPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<ShaderManager *,
                      NoRefCountPolicy, nsOSG        > SFUncountedShaderManagerPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderManager *,
                      RecordedRefCountPolicy, nsOSG  > MFRecShaderManagerPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderManager *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecShaderManagerPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderManager *,
                      WeakRefCountPolicy, nsOSG      > MFWeakShaderManagerPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<ShaderManager *,
                      NoRefCountPolicy, nsOSG        > MFUncountedShaderManagerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecShaderManagerPtr : 
    public PointerSField<ShaderManager *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecShaderManagerPtr : 
    public PointerSField<ShaderManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakShaderManagerPtr :
    public PointerSField<ShaderManager *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedShaderManagerPtr :
    public PointerSField<ShaderManager *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecShaderManagerPtr :
    public PointerMField<ShaderManager *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecShaderManagerPtr :
    public PointerMField<ShaderManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakShaderManagerPtr :
    public PointerMField<ShaderManager *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedShaderManagerPtr :
    public PointerMField<ShaderManager *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSHADERMANAGERFIELDS_H_ */
