/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class CapabilitiesDesc
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCAPABILITIESDESCBASE_H_
#define _OSGCAPABILITIESDESCBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

//#include "OSGBaseTypes.h"

#include "OSGFieldContainer.h" // Parent

#include "OSGSysFields.h"               // PlatformCapabilities type

#include "OSGCapabilitiesDescFields.h"

OSG_BEGIN_NAMESPACE


class CapabilitiesDesc;

//! \brief CapabilitiesDesc Base Class.

class OSG_CONTRIBTECHNIQUES_DLLMAPPING CapabilitiesDescBase : public FieldContainer
{
  public:

    typedef FieldContainer Inherited;
    typedef FieldContainer ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(CapabilitiesDesc);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        PlatformCapabilitiesFieldId = Inherited::NextFieldId,
        RequestedCapabilitiesFieldId = PlatformCapabilitiesFieldId + 1,
        RuntimeCapabilitiesFieldId = RequestedCapabilitiesFieldId + 1,
        NextFieldId = RuntimeCapabilitiesFieldId + 1
    };

    static const OSG::BitVector PlatformCapabilitiesFieldMask =
        (TypeTraits<BitVector>::One << PlatformCapabilitiesFieldId);
    static const OSG::BitVector RequestedCapabilitiesFieldMask =
        (TypeTraits<BitVector>::One << RequestedCapabilitiesFieldId);
    static const OSG::BitVector RuntimeCapabilitiesFieldMask =
        (TypeTraits<BitVector>::One << RuntimeCapabilitiesFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFUInt32          SFPlatformCapabilitiesType;
    typedef SFUInt32          SFRequestedCapabilitiesType;
    typedef SFUInt32          SFRuntimeCapabilitiesType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */


                  SFUInt32            *editSFPlatformCapabilities(void);
            const SFUInt32            *getSFPlatformCapabilities (void) const;

                  SFUInt32            *editSFRequestedCapabilities(void);
            const SFUInt32            *getSFRequestedCapabilities (void) const;

                  SFUInt32            *editSFRuntimeCapabilities(void);
            const SFUInt32            *getSFRuntimeCapabilities (void) const;


                  UInt32              &editPlatformCapabilities(void);
                  UInt32               getPlatformCapabilities (void) const;

                  UInt32              &editRequestedCapabilities(void);
                  UInt32               getRequestedCapabilities (void) const;

                  UInt32              &editRuntimeCapabilities(void);
                  UInt32               getRuntimeCapabilities (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setPlatformCapabilities(const UInt32 value);
            void setRequestedCapabilities(const UInt32 value);
            void setRuntimeCapabilities(const UInt32 value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual SizeT  getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  CapabilitiesDescTransitPtr  create          (void);
    static  CapabilitiesDesc           *createEmpty     (void);

    static  CapabilitiesDescTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  CapabilitiesDesc            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  CapabilitiesDescTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUInt32          _sfPlatformCapabilities;
    SFUInt32          _sfRequestedCapabilities;
    SFUInt32          _sfRuntimeCapabilities;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    CapabilitiesDescBase(void);
    CapabilitiesDescBase(const CapabilitiesDescBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~CapabilitiesDescBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

     GetFieldHandlePtr  getHandlePlatformCapabilities (void) const;
     EditFieldHandlePtr editHandlePlatformCapabilities(void);
     GetFieldHandlePtr  getHandleRequestedCapabilities (void) const;
     EditFieldHandlePtr editHandleRequestedCapabilities(void);
     GetFieldHandlePtr  getHandleRuntimeCapabilities (void) const;
     EditFieldHandlePtr editHandleRuntimeCapabilities(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      CapabilitiesDescBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const CapabilitiesDescBase &source);
};

typedef CapabilitiesDescBase *CapabilitiesDescBaseP;

OSG_END_NAMESPACE

#endif /* _OSGCAPABILITIESDESCBASE_H_ */
