/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDESCMATERIALMANAGERFIELDS_H_
#define _OSGDESCMATERIALMANAGERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class DescMaterialManager;

OSG_GEN_CONTAINERPTR(DescMaterialManager);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<DescMaterialManager *, nsOSG> :
    public FieldTraitsFCPtrBase<DescMaterialManager *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<DescMaterialManager *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakDescMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialManager *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdDescMaterialManagerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialManager *,
                      RecordedRefCountPolicy, nsOSG  > SFRecDescMaterialManagerPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialManager *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecDescMaterialManagerPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialManager *,
                      WeakRefCountPolicy, nsOSG      > SFWeakDescMaterialManagerPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialManager *,
                      NoRefCountPolicy, nsOSG        > SFUncountedDescMaterialManagerPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialManager *,
                      RecordedRefCountPolicy, nsOSG  > MFRecDescMaterialManagerPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialManager *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecDescMaterialManagerPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialManager *,
                      WeakRefCountPolicy, nsOSG      > MFWeakDescMaterialManagerPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialManager *,
                      NoRefCountPolicy, nsOSG        > MFUncountedDescMaterialManagerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecDescMaterialManagerPtr : 
    public PointerSField<DescMaterialManager *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecDescMaterialManagerPtr : 
    public PointerSField<DescMaterialManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakDescMaterialManagerPtr :
    public PointerSField<DescMaterialManager *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedDescMaterialManagerPtr :
    public PointerSField<DescMaterialManager *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecDescMaterialManagerPtr :
    public PointerMField<DescMaterialManager *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecDescMaterialManagerPtr :
    public PointerMField<DescMaterialManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakDescMaterialManagerPtr :
    public PointerMField<DescMaterialManager *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedDescMaterialManagerPtr :
    public PointerMField<DescMaterialManager *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGDESCMATERIALMANAGERFIELDS_H_ */
