/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGENVIRONMENTDESCFIELDS_H_
#define _OSGENVIRONMENTDESCFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class EnvironmentDesc;

OSG_GEN_CONTAINERPTR(EnvironmentDesc);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<EnvironmentDesc *, nsOSG> :
    public FieldTraitsFCPtrBase<EnvironmentDesc *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<EnvironmentDesc *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakEnvironmentDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<EnvironmentDesc *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdEnvironmentDescPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<EnvironmentDesc *,
                      RecordedRefCountPolicy, nsOSG  > SFRecEnvironmentDescPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<EnvironmentDesc *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecEnvironmentDescPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<EnvironmentDesc *,
                      WeakRefCountPolicy, nsOSG      > SFWeakEnvironmentDescPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<EnvironmentDesc *,
                      NoRefCountPolicy, nsOSG        > SFUncountedEnvironmentDescPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<EnvironmentDesc *,
                      RecordedRefCountPolicy, nsOSG  > MFRecEnvironmentDescPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<EnvironmentDesc *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecEnvironmentDescPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<EnvironmentDesc *,
                      WeakRefCountPolicy, nsOSG      > MFWeakEnvironmentDescPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<EnvironmentDesc *,
                      NoRefCountPolicy, nsOSG        > MFUncountedEnvironmentDescPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecEnvironmentDescPtr : 
    public PointerSField<EnvironmentDesc *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecEnvironmentDescPtr : 
    public PointerSField<EnvironmentDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakEnvironmentDescPtr :
    public PointerSField<EnvironmentDesc *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedEnvironmentDescPtr :
    public PointerSField<EnvironmentDesc *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecEnvironmentDescPtr :
    public PointerMField<EnvironmentDesc *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecEnvironmentDescPtr :
    public PointerMField<EnvironmentDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakEnvironmentDescPtr :
    public PointerMField<EnvironmentDesc *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedEnvironmentDescPtr :
    public PointerMField<EnvironmentDesc *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGENVIRONMENTDESCFIELDS_H_ */
