/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMULTILIGHTSHADOWPARAMETERFIELDS_H_
#define _OSGMULTILIGHTSHADOWPARAMETERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MultiLightShadowParameter;

OSG_GEN_CONTAINERPTR(MultiLightShadowParameter);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<MultiLightShadowParameter *, nsOSG> :
    public FieldTraitsFCPtrBase<MultiLightShadowParameter *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MultiLightShadowParameter *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMultiLightShadowParameterPtr"; 
}


/*! \ingroup GrpContribTechniquesFieldTraits
 */
template <>
struct FieldTraits<MultiLightShadowParameter *, nsOSG + 1> :
    public FieldTraitsFCPtrBase<MultiLightShadowParameter *, nsOSG + 1>
{
  private:

  public:
    typedef FieldTraits<MultiLightShadowParameter *, nsOSG + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildMultiLightShadowParameterPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameter *, nsOSG + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildMultiLightShadowParameterPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameter *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMultiLightShadowParameterPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameter *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMultiLightShadowParameterPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameter *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMultiLightShadowParameterPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameter *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMultiLightShadowParameterPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameter *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMultiLightShadowParameterPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameter *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMultiLightShadowParameterPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameter *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMultiLightShadowParameterPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameter *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMultiLightShadowParameterPtr;



/*! \ingroup GrpContribTechniquesFieldMFields */
typedef ChildPointerMField<
          MultiLightShadowParameter *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > MFUnrecChildMultiLightShadowParameterPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecMultiLightShadowParameterPtr : 
    public PointerSField<MultiLightShadowParameter *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecMultiLightShadowParameterPtr : 
    public PointerSField<MultiLightShadowParameter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakMultiLightShadowParameterPtr :
    public PointerSField<MultiLightShadowParameter *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedMultiLightShadowParameterPtr :
    public PointerSField<MultiLightShadowParameter *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecMultiLightShadowParameterPtr :
    public PointerMField<MultiLightShadowParameter *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecMultiLightShadowParameterPtr :
    public PointerMField<MultiLightShadowParameter *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakMultiLightShadowParameterPtr :
    public PointerMField<MultiLightShadowParameter *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedMultiLightShadowParameterPtr :
    public PointerMField<MultiLightShadowParameter *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecChildMultiLightShadowParameterPtr :
    public ChildPointerMField<
        MultiLightShadowParameter *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMULTILIGHTSHADOWPARAMETERFIELDS_H_ */
