/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMULTILIGHTSHADOWPARAMETERADVANCEDFIELDS_H_
#define _OSGMULTILIGHTSHADOWPARAMETERADVANCEDFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MultiLightShadowParameterAdvanced;

OSG_GEN_CONTAINERPTR(MultiLightShadowParameterAdvanced);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG> :
    public FieldTraitsFCPtrBase<MultiLightShadowParameterAdvanced *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMultiLightShadowParameterAdvancedPtr"; 
}


/*! \ingroup GrpContribTechniquesFieldTraits
 */
template <>
struct FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1> :
    public FieldTraitsFCPtrBase<MultiLightShadowParameterAdvanced *, nsOSG + 1>
{
  private:

  public:
    typedef FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildMultiLightShadowParameterAdvancedPtr"; 
}

template<> inline
const Char8 *FieldTraits<MultiLightShadowParameterAdvanced *, nsOSG + 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildMultiLightShadowParameterAdvancedPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameterAdvanced *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMultiLightShadowParameterAdvancedPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameterAdvanced *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMultiLightShadowParameterAdvancedPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameterAdvanced *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMultiLightShadowParameterAdvancedPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MultiLightShadowParameterAdvanced *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMultiLightShadowParameterAdvancedPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameterAdvanced *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMultiLightShadowParameterAdvancedPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameterAdvanced *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMultiLightShadowParameterAdvancedPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameterAdvanced *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMultiLightShadowParameterAdvancedPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MultiLightShadowParameterAdvanced *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMultiLightShadowParameterAdvancedPtr;



/*! \ingroup GrpContribTechniquesFieldMFields */
typedef ChildPointerMField<
          MultiLightShadowParameterAdvanced *, 
          UnrecordedRefCountPolicy,
          nsOSG + 1             > MFUnrecChildMultiLightShadowParameterAdvancedPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecMultiLightShadowParameterAdvancedPtr : 
    public PointerSField<MultiLightShadowParameterAdvanced *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecMultiLightShadowParameterAdvancedPtr : 
    public PointerSField<MultiLightShadowParameterAdvanced *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakMultiLightShadowParameterAdvancedPtr :
    public PointerSField<MultiLightShadowParameterAdvanced *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedMultiLightShadowParameterAdvancedPtr :
    public PointerSField<MultiLightShadowParameterAdvanced *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecMultiLightShadowParameterAdvancedPtr :
    public PointerMField<MultiLightShadowParameterAdvanced *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecMultiLightShadowParameterAdvancedPtr :
    public PointerMField<MultiLightShadowParameterAdvanced *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakMultiLightShadowParameterAdvancedPtr :
    public PointerMField<MultiLightShadowParameterAdvanced *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedMultiLightShadowParameterAdvancedPtr :
    public PointerMField<MultiLightShadowParameterAdvanced *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecChildMultiLightShadowParameterAdvancedPtr :
    public ChildPointerMField<
        MultiLightShadowParameterAdvanced *, 
        UnrecordedRefCountPolicy,
        nsOSG + 1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMULTILIGHTSHADOWPARAMETERADVANCEDFIELDS_H_ */
