/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class MultiLightShadowStageData!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"



#include "OSGShaderProgramChunk.h"      // OverrideProgChunk Class
#include "OSGShaderProgram.h"           // OverrideProgram Class

#include "OSGMultiLightShadowStageDataBase.h"
#include "OSGMultiLightShadowStageData.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::MultiLightShadowStageData
    View dependent Data used by the MultiLightShadowStage.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var UInt32          MultiLightShadowStageDataBase::_sfWidth
    
*/

/*! \var UInt32          MultiLightShadowStageDataBase::_sfHeight
    
*/

/*! \var ShaderProgramChunk * MultiLightShadowStageDataBase::_sfOverrideProgChunk
    
*/

/*! \var ShaderProgram * MultiLightShadowStageDataBase::_sfOverrideProgram
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<MultiLightShadowStageData *, nsOSG>::_type(
    "MultiLightShadowStageDataPtr", 
    "StageDataPtr", 
    MultiLightShadowStageData::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(MultiLightShadowStageData *, nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void MultiLightShadowStageDataBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "width",
        "",
        WidthFieldId, WidthFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&MultiLightShadowStageData::editHandleWidth),
        static_cast<FieldGetMethodSig >(&MultiLightShadowStageData::getHandleWidth));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "height",
        "",
        HeightFieldId, HeightFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&MultiLightShadowStageData::editHandleHeight),
        static_cast<FieldGetMethodSig >(&MultiLightShadowStageData::getHandleHeight));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecShaderProgramChunkPtr::Description(
        SFUnrecShaderProgramChunkPtr::getClassType(),
        "overrideProgChunk",
        "",
        OverrideProgChunkFieldId, OverrideProgChunkFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&MultiLightShadowStageData::editHandleOverrideProgChunk),
        static_cast<FieldGetMethodSig >(&MultiLightShadowStageData::getHandleOverrideProgChunk));

    oType.addInitialDesc(pDesc);

    pDesc = new SFUnrecShaderProgramPtr::Description(
        SFUnrecShaderProgramPtr::getClassType(),
        "overrideProgram",
        "",
        OverrideProgramFieldId, OverrideProgramFieldMask,
        true,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&MultiLightShadowStageData::editHandleOverrideProgram),
        static_cast<FieldGetMethodSig >(&MultiLightShadowStageData::getHandleOverrideProgram));

    oType.addInitialDesc(pDesc);
}


MultiLightShadowStageDataBase::TypeObject MultiLightShadowStageDataBase::_type(
    MultiLightShadowStageDataBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&MultiLightShadowStageDataBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&MultiLightShadowStageData::initMethod),
    reinterpret_cast<ExitContainerF>(&MultiLightShadowStageData::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&MultiLightShadowStageData::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"MultiLightShadowStageData\"\n"
    "   parent=\"StageData\"\n"
    "   library=\"ContribTechniques\"\n"
    "   pointerfieldtypes=\"none\"\n"
    "   structure=\"concrete\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   decoratable=\"false\"\n"
    "   useLocalIncludes=\"false\"\n"
    "   isNodeCore=\"false\"\n"
    "   >\n"
    "\n"
    "    View dependent Data used by the MultiLightShadowStage.\n"
    "\n"
    "  <Field\n"
    "\t name=\"width\"\n"
    "\t type=\"UInt32\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"external\"\n"
    "\t defaultValue=\"0\"\n"
    "\t access=\"public\"\n"
    "     >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"height\"\n"
    "\t type=\"UInt32\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"external\"\n"
    "\t defaultValue=\"0\"\n"
    "\t access=\"public\"\n"
    "     >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"overrideProgChunk\"\n"
    "\t type=\"ShaderProgramChunkPtr\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     >\n"
    "  </Field>\n"
    "  <Field\n"
    "\t name=\"overrideProgram\"\n"
    "\t type=\"ShaderProgramPtr\"\n"
    "\t cardinality=\"single\"\n"
    "\t visibility=\"internal\"\n"
    "\t defaultValue=\"NULL\"\n"
    "\t access=\"public\"\n"
    "     >\n"
    "  </Field>\n"
    "\n"
    "</FieldContainer>\n",
    "View dependent Data used by the MultiLightShadowStage.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &MultiLightShadowStageDataBase::getType(void)
{
    return _type;
}

const FieldContainerType &MultiLightShadowStageDataBase::getType(void) const
{
    return _type;
}

UInt32 MultiLightShadowStageDataBase::getContainerSize(void) const
{
    return sizeof(MultiLightShadowStageData);
}

/*------------------------- decorator get ------------------------------*/


SFUInt32 *MultiLightShadowStageDataBase::editSFWidth(void)
{
    editSField(WidthFieldMask);

    return &_sfWidth;
}

const SFUInt32 *MultiLightShadowStageDataBase::getSFWidth(void) const
{
    return &_sfWidth;
}


SFUInt32 *MultiLightShadowStageDataBase::editSFHeight(void)
{
    editSField(HeightFieldMask);

    return &_sfHeight;
}

const SFUInt32 *MultiLightShadowStageDataBase::getSFHeight(void) const
{
    return &_sfHeight;
}


//! Get the MultiLightShadowStageData::_sfOverrideProgChunk field.
const SFUnrecShaderProgramChunkPtr *MultiLightShadowStageDataBase::getSFOverrideProgChunk(void) const
{
    return &_sfOverrideProgChunk;
}

SFUnrecShaderProgramChunkPtr *MultiLightShadowStageDataBase::editSFOverrideProgChunk(void)
{
    editSField(OverrideProgChunkFieldMask);

    return &_sfOverrideProgChunk;
}

//! Get the value of the MultiLightShadowStageData::_sfOverrideProgChunk field.
ShaderProgramChunk * MultiLightShadowStageDataBase::getOverrideProgChunk(void) const
{
    return _sfOverrideProgChunk.getValue();
}

//! Set the value of the MultiLightShadowStageData::_sfOverrideProgChunk field.
void MultiLightShadowStageDataBase::setOverrideProgChunk(ShaderProgramChunk * const value)
{
    editSField(OverrideProgChunkFieldMask);

    _sfOverrideProgChunk.setValue(value);
}


//! Get the MultiLightShadowStageData::_sfOverrideProgram field.
const SFUnrecShaderProgramPtr *MultiLightShadowStageDataBase::getSFOverrideProgram(void) const
{
    return &_sfOverrideProgram;
}

SFUnrecShaderProgramPtr *MultiLightShadowStageDataBase::editSFOverrideProgram(void)
{
    editSField(OverrideProgramFieldMask);

    return &_sfOverrideProgram;
}

//! Get the value of the MultiLightShadowStageData::_sfOverrideProgram field.
ShaderProgram * MultiLightShadowStageDataBase::getOverrideProgram(void) const
{
    return _sfOverrideProgram.getValue();
}

//! Set the value of the MultiLightShadowStageData::_sfOverrideProgram field.
void MultiLightShadowStageDataBase::setOverrideProgram(ShaderProgram * const value)
{
    editSField(OverrideProgramFieldMask);

    _sfOverrideProgram.setValue(value);
}






/*------------------------------ access -----------------------------------*/

SizeT MultiLightShadowStageDataBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (WidthFieldMask & whichField))
    {
        returnValue += _sfWidth.getBinSize();
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        returnValue += _sfHeight.getBinSize();
    }
    if(FieldBits::NoField != (OverrideProgChunkFieldMask & whichField))
    {
        returnValue += _sfOverrideProgChunk.getBinSize();
    }
    if(FieldBits::NoField != (OverrideProgramFieldMask & whichField))
    {
        returnValue += _sfOverrideProgram.getBinSize();
    }

    return returnValue;
}

void MultiLightShadowStageDataBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (WidthFieldMask & whichField))
    {
        _sfWidth.copyToBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        _sfHeight.copyToBin(pMem);
    }
    if(FieldBits::NoField != (OverrideProgChunkFieldMask & whichField))
    {
        _sfOverrideProgChunk.copyToBin(pMem);
    }
    if(FieldBits::NoField != (OverrideProgramFieldMask & whichField))
    {
        _sfOverrideProgram.copyToBin(pMem);
    }
}

void MultiLightShadowStageDataBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (WidthFieldMask & whichField))
    {
        editSField(WidthFieldMask);
        _sfWidth.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (HeightFieldMask & whichField))
    {
        editSField(HeightFieldMask);
        _sfHeight.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (OverrideProgChunkFieldMask & whichField))
    {
        editSField(OverrideProgChunkFieldMask);
        _sfOverrideProgChunk.copyFromBin(pMem);
    }
    if(FieldBits::NoField != (OverrideProgramFieldMask & whichField))
    {
        editSField(OverrideProgramFieldMask);
        _sfOverrideProgram.copyFromBin(pMem);
    }
}

//! create a new instance of the class
MultiLightShadowStageDataTransitPtr MultiLightShadowStageDataBase::createLocal(BitVector bFlags)
{
    MultiLightShadowStageDataTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<MultiLightShadowStageData>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
MultiLightShadowStageDataTransitPtr MultiLightShadowStageDataBase::createDependent(BitVector bFlags)
{
    MultiLightShadowStageDataTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<MultiLightShadowStageData>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
MultiLightShadowStageDataTransitPtr MultiLightShadowStageDataBase::create(void)
{
    MultiLightShadowStageDataTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<MultiLightShadowStageData>(tmpPtr);
    }

    return fc;
}

MultiLightShadowStageData *MultiLightShadowStageDataBase::createEmptyLocal(BitVector bFlags)
{
    MultiLightShadowStageData *returnValue;

    newPtr<MultiLightShadowStageData>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
MultiLightShadowStageData *MultiLightShadowStageDataBase::createEmpty(void)
{
    MultiLightShadowStageData *returnValue;

    newPtr<MultiLightShadowStageData>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr MultiLightShadowStageDataBase::shallowCopyLocal(
    BitVector bFlags) const
{
    MultiLightShadowStageData *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const MultiLightShadowStageData *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr MultiLightShadowStageDataBase::shallowCopyDependent(
    BitVector bFlags) const
{
    MultiLightShadowStageData *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const MultiLightShadowStageData *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr MultiLightShadowStageDataBase::shallowCopy(void) const
{
    MultiLightShadowStageData *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const MultiLightShadowStageData *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

MultiLightShadowStageDataBase::MultiLightShadowStageDataBase(void) :
    Inherited(),
    _sfWidth                  (UInt32(0)),
    _sfHeight                 (UInt32(0)),
    _sfOverrideProgChunk      (NULL),
    _sfOverrideProgram        (NULL)
{
}

MultiLightShadowStageDataBase::MultiLightShadowStageDataBase(const MultiLightShadowStageDataBase &source) :
    Inherited(source),
    _sfWidth                  (source._sfWidth                  ),
    _sfHeight                 (source._sfHeight                 ),
    _sfOverrideProgChunk      (NULL),
    _sfOverrideProgram        (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

MultiLightShadowStageDataBase::~MultiLightShadowStageDataBase(void)
{
}

void MultiLightShadowStageDataBase::onCreate(const MultiLightShadowStageData *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        MultiLightShadowStageData *pThis = static_cast<MultiLightShadowStageData *>(this);

        pThis->setOverrideProgChunk(source->getOverrideProgChunk());

        pThis->setOverrideProgram(source->getOverrideProgram());
    }
}

GetFieldHandlePtr MultiLightShadowStageDataBase::getHandleWidth           (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfWidth,
             this->getType().getFieldDesc(WidthFieldId),
             const_cast<MultiLightShadowStageDataBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr MultiLightShadowStageDataBase::editHandleWidth          (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfWidth,
             this->getType().getFieldDesc(WidthFieldId),
             this));


    editSField(WidthFieldMask);

    return returnValue;
}

GetFieldHandlePtr MultiLightShadowStageDataBase::getHandleHeight          (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             const_cast<MultiLightShadowStageDataBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr MultiLightShadowStageDataBase::editHandleHeight         (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfHeight,
             this->getType().getFieldDesc(HeightFieldId),
             this));


    editSField(HeightFieldMask);

    return returnValue;
}

GetFieldHandlePtr MultiLightShadowStageDataBase::getHandleOverrideProgChunk (void) const
{
    SFUnrecShaderProgramChunkPtr::GetHandlePtr returnValue(
        new  SFUnrecShaderProgramChunkPtr::GetHandle(
             &_sfOverrideProgChunk,
             this->getType().getFieldDesc(OverrideProgChunkFieldId),
             const_cast<MultiLightShadowStageDataBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr MultiLightShadowStageDataBase::editHandleOverrideProgChunk(void)
{
    SFUnrecShaderProgramChunkPtr::EditHandlePtr returnValue(
        new  SFUnrecShaderProgramChunkPtr::EditHandle(
             &_sfOverrideProgChunk,
             this->getType().getFieldDesc(OverrideProgChunkFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&MultiLightShadowStageData::setOverrideProgChunk,
                    static_cast<MultiLightShadowStageData *>(this), _1));

    editSField(OverrideProgChunkFieldMask);

    return returnValue;
}

GetFieldHandlePtr MultiLightShadowStageDataBase::getHandleOverrideProgram (void) const
{
    SFUnrecShaderProgramPtr::GetHandlePtr returnValue(
        new  SFUnrecShaderProgramPtr::GetHandle(
             &_sfOverrideProgram,
             this->getType().getFieldDesc(OverrideProgramFieldId),
             const_cast<MultiLightShadowStageDataBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr MultiLightShadowStageDataBase::editHandleOverrideProgram(void)
{
    SFUnrecShaderProgramPtr::EditHandlePtr returnValue(
        new  SFUnrecShaderProgramPtr::EditHandle(
             &_sfOverrideProgram,
             this->getType().getFieldDesc(OverrideProgramFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&MultiLightShadowStageData::setOverrideProgram,
                    static_cast<MultiLightShadowStageData *>(this), _1));

    editSField(OverrideProgramFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void MultiLightShadowStageDataBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    MultiLightShadowStageData *pThis = static_cast<MultiLightShadowStageData *>(this);

    pThis->execSync(static_cast<MultiLightShadowStageData *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *MultiLightShadowStageDataBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    MultiLightShadowStageData *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const MultiLightShadowStageData *>(pRefAspect),
                  dynamic_cast<const MultiLightShadowStageData *>(this));

    return returnValue;
}
#endif

void MultiLightShadowStageDataBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<MultiLightShadowStageData *>(this)->setOverrideProgChunk(NULL);

    static_cast<MultiLightShadowStageData *>(this)->setOverrideProgram(NULL);


}


OSG_END_NAMESPACE
