/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGHDR2STAGEFIELDS_H_
#define _OSGHDR2STAGEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGEffectGroupsDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class HDR2Stage;

OSG_GEN_CONTAINERPTR(HDR2Stage);
/*! \ingroup GrpEffectsGroupsHDRFieldTraits
    \ingroup GrpLibOSGEffectGroups
 */
template <>
struct FieldTraits<HDR2Stage *, nsOSG> :
    public FieldTraitsFCPtrBase<HDR2Stage *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<HDR2Stage *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_EFFECTGROUPS_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakHDR2StagePtr"; 
}

template<> inline
const Char8 *FieldTraits<HDR2Stage *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdHDR2StagePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpEffectsGroupsHDRFieldSFields */
typedef PointerSField<HDR2Stage *,
                      RecordedRefCountPolicy, nsOSG  > SFRecHDR2StagePtr;
/*! \ingroup GrpEffectsGroupsHDRFieldSFields */
typedef PointerSField<HDR2Stage *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecHDR2StagePtr;
/*! \ingroup GrpEffectsGroupsHDRFieldSFields */
typedef PointerSField<HDR2Stage *,
                      WeakRefCountPolicy, nsOSG      > SFWeakHDR2StagePtr;
/*! \ingroup GrpEffectsGroupsHDRFieldSFields */
typedef PointerSField<HDR2Stage *,
                      NoRefCountPolicy, nsOSG        > SFUncountedHDR2StagePtr;


/*! \ingroup GrpEffectsGroupsHDRFieldMFields */
typedef PointerMField<HDR2Stage *,
                      RecordedRefCountPolicy, nsOSG  > MFRecHDR2StagePtr;
/*! \ingroup GrpEffectsGroupsHDRFieldMFields */
typedef PointerMField<HDR2Stage *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecHDR2StagePtr;
/*! \ingroup GrpEffectsGroupsHDRFieldMFields */
typedef PointerMField<HDR2Stage *,
                      WeakRefCountPolicy, nsOSG      > MFWeakHDR2StagePtr;
/*! \ingroup GrpEffectsGroupsHDRFieldMFields */
typedef PointerMField<HDR2Stage *,
                      NoRefCountPolicy, nsOSG        > MFUncountedHDR2StagePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpEffectsGroupsHDRFieldSFields \ingroup GrpLibOSGEffectGroups */
struct SFRecHDR2StagePtr : 
    public PointerSField<HDR2Stage *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpEffectsGroupsHDRFieldSFields \ingroup GrpLibOSGEffectGroups */
struct SFUnrecHDR2StagePtr : 
    public PointerSField<HDR2Stage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpEffectsGroupsHDRFieldSFields \ingroup GrpLibOSGEffectGroups */
struct SFWeakHDR2StagePtr :
    public PointerSField<HDR2Stage *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpEffectsGroupsHDRFieldSFields \ingroup GrpLibOSGEffectGroups */
struct SFUncountedHDR2StagePtr :
    public PointerSField<HDR2Stage *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpEffectsGroupsHDRFieldMFields \ingroup GrpLibOSGEffectGroups */
struct MFRecHDR2StagePtr :
    public PointerMField<HDR2Stage *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpEffectsGroupsHDRFieldMFields \ingroup GrpLibOSGEffectGroups */
struct MFUnrecHDR2StagePtr :
    public PointerMField<HDR2Stage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpEffectsGroupsHDRFieldMFields \ingroup GrpLibOSGEffectGroups */
struct MFWeakHDR2StagePtr :
    public PointerMField<HDR2Stage *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpEffectsGroupsHDRFieldMFields \ingroup GrpLibOSGEffectGroups */
struct MFUncountedHDR2StagePtr :
    public PointerMField<HDR2Stage *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGHDR2STAGEFIELDS_H_ */
