/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2002 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact: dirk@opensg.org, gerrit.voss@vossg.org, jbehr@zgdv.de          *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

//---------------------------------------------------------------------------
//  Includes
//---------------------------------------------------------------------------

#include <cstdlib>
#include <cstdio>
#include <algorithm>
#include <boost/functional/hash/hash.hpp>

#include "OSGConfig.h"
#include "OSGLog.h"
#include "OSGImageFormat.h"
#include "OSGWindow.h"

OSG_BEGIN_NAMESPACE

ImageFormat::FormatInfo ImageFormat::_formatInfo[ImageFormat::FORMAT_COUNT] =
{
    /*FORMAT_UNDEFINED                     */{  0, Vec3ub( 0, 0, 0), 0, Vec4ub(0,             0,              0,             0            ), 0},

    /*FORMAT_RG4_UNORM_PACK8               */{  1, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_PACKED8_BIT  | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA4_UNORM_PACK16            */{  2, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGRA4_UNORM_PACK16            */{  2, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_R5G6B5_UNORM_PACK16           */{  2, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_B5G6R5_UNORM_PACK16           */{  2, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGB5A1_UNORM_PACK16           */{  2, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR5A1_UNORM_PACK16           */{  2, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_A1RGB5_UNORM_PACK16           */{  2, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_ALPHA, SWIZZLE_RED,    SWIZZLE_GREEN, SWIZZLE_BLUE ), CAP_PACKED16_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_R8_UNORM_PACK8                */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_R8_SNORM_PACK8                */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT},
    /*FORMAT_R8_USCALED_PACK8              */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R8_SSCALED_PACK8              */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R8_UINT_PACK8                 */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT},
    /*FORMAT_R8_SINT_PACK8                 */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_SIGNED_BIT},
    /*FORMAT_R8_SRGB_PACK8                 */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RG8_UNORM_PACK8               */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RG8_SNORM_PACK8               */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RG8_USCALED_PACK8             */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG8_SSCALED_PACK8             */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG8_UINT_PACK8                */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT},
    /*FORMAT_RG8_SINT_PACK8                */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_SIGNED_BIT},
    /*FORMAT_RG8_SRGB_PACK8                */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_COLORSPACE_SRGB_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGB8_UNORM_PACK8              */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB8_SNORM_PACK8              */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB8_USCALED_PACK8            */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB8_SSCALED_PACK8            */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB8_UINT_PACK8               */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB8_SINT_PACK8               */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_SIGNED_BIT   | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB8_SRGB_PACK8               */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_BGR8_UNORM_PACK8              */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR8_SNORM_PACK8              */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR8_USCALED_PACK8            */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR8_SSCALED_PACK8            */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR8_UINT_PACK8               */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR8_SINT_PACK8               */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR8_SRGB_PACK8               */{  3, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGBA8_UNORM_PACK8             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA8_SNORM_PACK8             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RGBA8_USCALED_PACK8           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_SSCALED_PACK8           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_UINT_PACK8              */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA8_SINT_PACK8              */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_SIGNED_BIT},
    /*FORMAT_RGBA8_SRGB_PACK8              */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_COLORSPACE_SRGB_BIT},

    /*FORMAT_BGRA8_UNORM_PACK8             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT},
    /*FORMAT_BGRA8_SNORM_PACK8             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGRA8_USCALED_PACK8           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGRA8_SSCALED_PACK8           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGRA8_UINT_PACK8              */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGRA8_SINT_PACK8              */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGRA8_SRGB_PACK8              */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_SWIZZLE_BIT},

    /*FORMAT_RGBA8_UNORM_PACK32            */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_SNORM_PACK32            */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_USCALED_PACK32          */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_SSCALED_PACK32          */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_UINT_PACK32             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_SINT_PACK32             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_SIGNED_BIT   | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA8_SRGB_PACK32             */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_SWIZZLE_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGB10A2_UNORM_PACK32          */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_PACKED32_BIT},
    /*FORMAT_RGB10A2_SNORM_PACK32          */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB10A2_USCALED_PACK32        */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB10A2_SSCALED_PACK32        */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB10A2_UINT_PACK32           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_PACKED32_BIT},
    /*FORMAT_RGB10A2_SINT_PACK32           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_SIGNED_BIT   | CAP_PACKED32_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_BGR10A2_UNORM_PACK32          */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_PACKED32_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR10A2_SNORM_PACK32          */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT   | CAP_PACKED32_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR10A2_USCALED_PACK32        */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_PACKED32_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR10A2_SSCALED_PACK32        */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_SIGNED_BIT   | CAP_PACKED32_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR10A2_UINT_PACK32           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_PACKED32_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_BGR10A2_SINT_PACK32           */{  4, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_SIGNED_BIT   | CAP_PACKED32_BIT | CAP_SWIZZLE_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_R16_UNORM_PACK16              */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_R16_SNORM_PACK16              */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT},
    /*FORMAT_R16_USCALED_PACK16            */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R16_SSCALED_PACK16            */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R16_UINT_PACK16               */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT},
    /*FORMAT_R16_SINT_PACK16               */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_SIGNED_BIT},
    /*FORMAT_R16_SFLOAT_PACK16             */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_FLOAT_BIT      | CAP_SIGNED_BIT},

    /*FORMAT_RG16_UNORM_PACK16             */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RG16_SNORM_PACK16             */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RG16_USCALED_PACK16           */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG16_SSCALED_PACK16           */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_SCALED_BIT | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG16_UINT_PACK16              */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RG16_SINT_PACK16              */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RG16_SFLOAT_PACK16            */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_FLOAT_BIT | CAP_SIGNED_BIT},

    /*FORMAT_RGB16_UNORM_PACK16            */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB16_SNORM_PACK16            */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB16_USCALED_PACK16          */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB16_SSCALED_PACK16          */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_SCALED_BIT     | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB16_UINT_PACK16             */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB16_SINT_PACK16             */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT    | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB16_SFLOAT_PACK16           */{  6, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_FLOAT_BIT      | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGBA16_UNORM_PACK16           */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA16_SNORM_PACK16           */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_NORMALIZED_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RGBA16_USCALED_PACK16         */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA16_SSCALED_PACK16         */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_SCALED_BIT     | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA16_UINT_PACK16            */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA16_SINT_PACK16            */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT    | CAP_SIGNED_BIT},
    /*FORMAT_RGBA16_SFLOAT_PACK16          */{  8, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_FLOAT_BIT      | CAP_SIGNED_BIT},

    /*FORMAT_R32_UINT_PACK32               */{  4, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_R32_SINT_PACK32               */{  4, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT},
    /*FORMAT_R32_SFLOAT_PACK32             */{  4, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_FLOAT_BIT   | CAP_SIGNED_BIT},

    /*FORMAT_RG32_UINT_PACK32              */{  8, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RG32_SINT_PACK32              */{  8, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RG32_SFLOAT_PACK32            */{  8, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_FLOAT_BIT   | CAP_SIGNED_BIT},

    /*FORMAT_RGB32_UINT_PACK32             */{ 12, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGB32_SINT_PACK32             */{ 12, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RGB32_SFLOAT_PACK32           */{ 12, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_FLOAT_BIT   | CAP_SIGNED_BIT},

    /*FORMAT_RGBA32_UINT_PACK32            */{ 16, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA32_SINT_PACK32            */{ 16, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RGBA32_SFLOAT_PACK32          */{ 16, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_FLOAT_BIT   | CAP_SIGNED_BIT},

    /*FORMAT_R64_UINT_PACK64               */{  8, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R64_SINT_PACK64               */{  8, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R64_SFLOAT_PACK64             */{  8, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_FLOAT_BIT   | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RG64_UINT_PACK64              */{ 16, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG64_SINT_PACK64              */{ 16, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG64_SFLOAT_PACK64            */{ 16, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_FLOAT_BIT   | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGB64_UINT_PACK64             */{ 24, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB64_SINT_PACK64             */{ 24, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_INTEGER_BIT | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB64_SFLOAT_PACK64           */{ 24, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_FLOAT_BIT   | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGBA64_UINT_PACK64            */{ 32, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA64_SINT_PACK64            */{ 32, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_INTEGER_BIT | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA64_SFLOAT_PACK64          */{ 32, Vec3ub( 1, 1, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_FLOAT_BIT   | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RG11B10_UFLOAT_PACK32         */{  4, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_PACKED32_BIT | CAP_FLOAT_BIT | CAP_SIGNED_BIT},
    /*FORMAT_RGB9E5_UFLOAT_PACK32          */{  4, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_PACKED32_BIT | CAP_FLOAT_BIT | CAP_UNSIGNED_BIT},

    /*FORMAT_D16_UNORM_PACK16              */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_INTEGER_BIT},
    /*FORMAT_D24_UNORM_PACK32              */{  4, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_INTEGER_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_D32_SFLOAT_PACK32             */{  4, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_FLOAT_BIT},
    /*FORMAT_S8_UINT_PACK8                 */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_STENCIL_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_D16_UNORM_S8_UINT_PACK32      */{  3, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_INTEGER_BIT | CAP_STENCIL_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_D24_UNORM_S8_UINT_PACK32      */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_INTEGER_BIT | CAP_STENCIL_BIT},
    /*FORMAT_D32_SFLOAT_S8_UINT_PACK64     */{  5, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_DEPTH_BIT | CAP_FLOAT_BIT | CAP_STENCIL_BIT},

    /*FORMAT_RGB_DXT1_UNORM_BLOCK8         */{  8, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB_DXT1_SRGB_BLOCK8          */{  8, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_DXT1_UNORM_BLOCK8        */{  8, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_DXT1_SRGB_BLOCK8         */{  8, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_DXT3_UNORM_BLOCK16       */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_DXT3_SRGB_BLOCK16        */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_DXT5_UNORM_BLOCK16       */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_DXT5_SRGB_BLOCK16        */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_R_ATI1N_UNORM_BLOCK8          */{  8, Vec3ub( 4, 4, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_R_ATI1N_SNORM_BLOCK8          */{  8, Vec3ub( 4, 4, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_SIGNED_BIT},
    /*FORMAT_RG_ATI2N_UNORM_BLOCK16        */{ 16, Vec3ub( 4, 4, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RG_ATI2N_SNORM_BLOCK16        */{ 16, Vec3ub( 4, 4, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_SIGNED_BIT},
    /*FORMAT_RGB_BP_UFLOAT_BLOCK16         */{ 16, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_FLOAT_BIT           | CAP_UNSIGNED_BIT},
    /*FORMAT_RGB_BP_SFLOAT_BLOCK16         */{ 16, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_FLOAT_BIT           | CAP_SIGNED_BIT},
    /*FORMAT_RGBA_BP_UNORM_BLOCK16         */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_BP_SRGB_BLOCK16          */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},

    /*FORMAT_RGB_ETC2_UNORM_BLOCK8         */{  8, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB_ETC2_SRGB_BLOCK8          */{  8, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_ETC2_UNORM_BLOCK8        */{  8, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_ETC2_SRGB_BLOCK8         */{  8, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_ETC2_UNORM_BLOCK16       */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_ETC2_SRGB_BLOCK16        */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R_EAC_UNORM_BLOCK8            */{  8, Vec3ub( 4, 4, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_R_EAC_SNORM_BLOCK8            */{  8, Vec3ub( 4, 4, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG_EAC_UNORM_BLOCK16          */{ 16, Vec3ub( 4, 4, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RG_EAC_SNORM_BLOCK16          */{ 16, Vec3ub( 4, 4, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_ZERO,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_SIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGBA_ASTC_4X4_UNORM_BLOCK16   */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_4X4_SRGB_BLOCK16    */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_5X4_UNORM_BLOCK16   */{ 16, Vec3ub( 5, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_5X4_SRGB_BLOCK16    */{ 16, Vec3ub( 5, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_5X5_UNORM_BLOCK16   */{ 16, Vec3ub( 5, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_5X5_SRGB_BLOCK16    */{ 16, Vec3ub( 5, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_6X5_UNORM_BLOCK16   */{ 16, Vec3ub( 6, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_6X5_SRGB_BLOCK16    */{ 16, Vec3ub( 6, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_6X6_UNORM_BLOCK16   */{ 16, Vec3ub( 6, 6, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_6X6_SRGB_BLOCK16    */{ 16, Vec3ub( 6, 6, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_8X5_UNORM_BLOCK16   */{ 16, Vec3ub( 8, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_8X5_SRGB_BLOCK16    */{ 16, Vec3ub( 8, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_8X6_UNORM_BLOCK16   */{ 16, Vec3ub( 8, 6, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_8X6_SRGB_BLOCK16    */{ 16, Vec3ub( 8, 6, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_8X8_UNORM_BLOCK16   */{ 16, Vec3ub( 8, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_8X8_SRGB_BLOCK16    */{ 16, Vec3ub( 8, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X5_UNORM_BLOCK16  */{ 16, Vec3ub(10, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X5_SRGB_BLOCK16   */{ 16, Vec3ub(10, 5, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X6_UNORM_BLOCK16  */{ 16, Vec3ub(10, 6, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X6_SRGB_BLOCK16   */{ 16, Vec3ub(10, 6, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X8_UNORM_BLOCK16  */{ 16, Vec3ub(10, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X8_SRGB_BLOCK16   */{ 16, Vec3ub(10, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X10_UNORM_BLOCK16 */{ 16, Vec3ub(10,10, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_10X10_SRGB_BLOCK16  */{ 16, Vec3ub(10,10, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_12X10_UNORM_BLOCK16 */{ 16, Vec3ub(12,10, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_12X10_SRGB_BLOCK16  */{ 16, Vec3ub(12,10, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_12X12_UNORM_BLOCK16 */{ 16, Vec3ub(12,12, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT},
    /*FORMAT_RGBA_ASTC_12X12_SRGB_BLOCK16  */{ 16, Vec3ub(12,12, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT},

    /*FORMAT_RGB_PVRTC1_8X8_UNORM_BLOCK32  */{ 32, Vec3ub( 8, 8, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB_PVRTC1_8X8_SRGB_BLOCK32   */{ 32, Vec3ub( 8, 8, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB_PVRTC1_16X8_UNORM_BLOCK32 */{ 32, Vec3ub(16, 8, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB_PVRTC1_16X8_SRGB_BLOCK32  */{ 32, Vec3ub(16, 8, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC1_8X8_UNORM_BLOCK32 */{ 32, Vec3ub( 8, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC1_8X8_SRGB_BLOCK32  */{ 32, Vec3ub( 8, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC1_16X8_UNORM_BLOCK32*/{ 32, Vec3ub(16, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC1_16X8_SRGB_BLOCK32 */{ 32, Vec3ub(16, 8, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC2_4X4_UNORM_BLOCK8  */{  8, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC2_4X4_SRGB_BLOCK8   */{  8, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC2_8X4_UNORM_BLOCK8  */{  8, Vec3ub( 8, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT      | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_PVRTC2_8X4_SRGB_BLOCK8   */{  8, Vec3ub( 8, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_COLORSPACE_SRGB_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_RGB_ETC_UNORM_BLOCK8          */{  8, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGB_ATC_UNORM_BLOCK8          */{  8, Vec3ub( 4, 4, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_ATCA_UNORM_BLOCK16       */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_RGBA_ATCI_UNORM_BLOCK16       */{ 16, Vec3ub( 4, 4, 1), 4, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ALPHA), CAP_COMPRESSED_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_L8_UNORM_PACK8                */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_RED,    SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_LUMINANCE_ALPHA_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_A8_UNORM_PACK8                */{  1, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_ZERO,  SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_RED  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_LUMINANCE_ALPHA_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_LA8_UNORM_PACK8               */{  2, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_RED,    SWIZZLE_RED,   SWIZZLE_GREEN), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_LUMINANCE_ALPHA_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_L16_UNORM_PACK16              */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_RED,   SWIZZLE_RED,    SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_LUMINANCE_ALPHA_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_A16_UNORM_PACK16              */{  2, Vec3ub( 1, 1, 1), 1, Vec4ub(SWIZZLE_ZERO,  SWIZZLE_ZERO,   SWIZZLE_ZERO,  SWIZZLE_RED  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_LUMINANCE_ALPHA_BIT | CAP_DDS_GLI_EXT_BIT},
    /*FORMAT_LA16_UNORM_PACK16             */{  4, Vec3ub( 1, 1, 1), 2, Vec4ub(SWIZZLE_RED,   SWIZZLE_RED,    SWIZZLE_RED,   SWIZZLE_GREEN), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_LUMINANCE_ALPHA_BIT | CAP_DDS_GLI_EXT_BIT},

    /*FORMAT_BGR8_UNORM_PACK32             */{  4, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT},
    /*FORMAT_BGR8_SRGB_PACK32              */{  4, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_BLUE,  SWIZZLE_GREEN,  SWIZZLE_RED,   SWIZZLE_ONE  ), CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_SWIZZLE_BIT | CAP_COLORSPACE_SRGB_BIT},

    /*FORMAT_RG3B2_UNORM_PACK8             */{  1, Vec3ub( 1, 1, 1), 3, Vec4ub(SWIZZLE_RED,   SWIZZLE_GREEN,  SWIZZLE_BLUE,  SWIZZLE_ONE  ), CAP_PACKED8_BIT | CAP_NORMALIZED_BIT | CAP_UNSIGNED_BIT | CAP_DDS_GLI_EXT_BIT},
};

ImageFormat::GlSwizzle ImageFormat::_swizzleInfo[SWIZZLE_COUNT] =
{
    OGL_SWIZZLE_RED,
    OGL_SWIZZLE_GREEN,
    OGL_SWIZZLE_BLUE,
    OGL_SWIZZLE_ALPHA,
    OGL_SWIZZLE_ZERO,
    OGL_SWIZZLE_ONE
};

std::vector<ImageFormat::FormatDesc> ImageFormat::_formatDesc;

bool ImageFormat::hasSwizzle()
{
    bool has_swizzles = false;

#ifdef OSG_OGL_TEXTURE_SWIZZLE
    Int32 extIdx = Window::getExtensionIdX("GL_ARB_texture_swizzle");
    bool  hasExt = Window::hasCommonExtension(extIdx);
#endif

    return has_swizzles;
}

void ImageFormat::initializeFormatDesc()
{
    if (_formatDesc.empty())
    {
        bool swizzle = hasSwizzle();

        bool es20 = false;
#ifdef OSG_OGL_ES2
        es20 = true;
#endif
        const GlExternalFormat ogl_external_BGR              = swizzle ? OGL_EXTERNAL_RGB          : OGL_EXTERNAL_BGR;
        const GlExternalFormat ogl_external_BGRA             = swizzle ? OGL_EXTERNAL_RGBA         : OGL_EXTERNAL_BGRA;
        const GlExternalFormat ogl_external_BGRInt           = swizzle ? OGL_EXTERNAL_RGB_INTEGER  : OGL_EXTERNAL_BGR_INTEGER;
        const GlExternalFormat ogl_external_BGRAInt          = swizzle ? OGL_EXTERNAL_RGBA_INTEGER : OGL_EXTERNAL_BGRA_INTEGER;

        const GlExternalFormat ogl_external_SRGB8            = !es20   ? OGL_EXTERNAL_RGB          : OGL_EXTERNAL_SRGB_EXT;
        const GlExternalFormat ogl_external_SRGB8_A8         = !es20   ? OGL_EXTERNAL_RGBA         : OGL_EXTERNAL_SRGB_ALPHA_EXT;

        const GlExternalFormat ogl_external_Luminance        = swizzle ? OGL_EXTERNAL_RED          : OGL_EXTERNAL_LUMINANCE;
        const GlExternalFormat ogl_external_Alpha            = swizzle ? OGL_EXTERNAL_RED          : OGL_EXTERNAL_ALPHA;
        const GlExternalFormat ogl_external_LuminanceAlpha   = swizzle ? OGL_EXTERNAL_RG           : OGL_EXTERNAL_LUMINANCE_ALPHA;

        const GlInternalFormat ogl_internal_BGRA             = es20    ? OGL_INTERNAL_BGRA8_UNORM  : OGL_INTERNAL_RGBA8_UNORM;
        const GlInternalFormat ogl_internal_RGBETC           = es20    ? OGL_INTERNAL_RGB_ETC      : OGL_INTERNAL_RGB_ETC2;

        const GlInternalFormat ogl_internal_Luminance8       = swizzle ? OGL_INTERNAL_R8_UNORM     : OGL_INTERNAL_LUMINANCE8;
        const GlInternalFormat ogl_internal_Alpha8           = swizzle ? OGL_INTERNAL_R8_UNORM     : OGL_INTERNAL_ALPHA8;
        const GlInternalFormat ogl_internal_LuminanceAlpha8  = swizzle ? OGL_INTERNAL_RG8_UNORM    : OGL_INTERNAL_LUMINANCE8_ALPHA8;

        const GlInternalFormat ogl_internal_Luminance16      = swizzle ? OGL_INTERNAL_R16_UNORM    : OGL_INTERNAL_LUMINANCE16;
        const GlInternalFormat ogl_internal_Alpha16          = swizzle ? OGL_INTERNAL_R16_UNORM    : OGL_INTERNAL_ALPHA16;
        const GlInternalFormat ogl_internal_LuminanceAlpha16 = swizzle ? OGL_INTERNAL_RG16_UNORM   : OGL_INTERNAL_LUMINANCE16_ALPHA16;

        const GlTypeFormat     ogl_type_F16                  = es20    ? OGL_TYPE_F16_OES          : OGL_TYPE_F16;

        FormatDesc formatDesc[FORMAT_COUNT] =
        {
            /*FORMAT_UNDEFINED                     */{OGL_INTERNAL_NONE,                             OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},

            /*FORMAT_RG4_UNORM_PACK8               */{OGL_INTERNAL_RG4_EXT,                          OGL_EXTERNAL_RG,                OGL_TYPE_UINT8_RG4_REV_GTC,     0},
            /*FORMAT_RGBA4_UNORM_PACK16            */{OGL_INTERNAL_RGBA4,                            OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT16_RGBA4_REV,      0},
            /*FORMAT_BGRA4_UNORM_PACK16            */{OGL_INTERNAL_RGBA4,                            OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT16_RGBA4,          FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_R5G6B5_UNORM_PACK16           */{OGL_INTERNAL_R5G6B5,                           OGL_EXTERNAL_RGB,               OGL_TYPE_UINT16_R5G6B5_REV,     0},
            /*FORMAT_B5G6R5_UNORM_PACK16           */{OGL_INTERNAL_R5G6B5,                           OGL_EXTERNAL_RGB,               OGL_TYPE_UINT16_R5G6B5,         FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_RGB5A1_UNORM_PACK16           */{OGL_INTERNAL_RGB5A1,                           OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT16_RGB5A1_REV,     0},
            /*FORMAT_BGR5A1_UNORM_PACK16           */{OGL_INTERNAL_RGB5A1,                           OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT16_RGB5A1,         FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_A1RGB5_UNORM_PACK16           */{OGL_INTERNAL_RGB5A1,                           OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT16_A1RGB5_GTC,     0},

            /*FORMAT_R8_UNORM_PACK8                */{OGL_INTERNAL_R8_UNORM,                         OGL_EXTERNAL_RED,               OGL_TYPE_U8,                    0},
            /*FORMAT_R8_SNORM_PACK8                */{OGL_INTERNAL_R8_SNORM,                         OGL_EXTERNAL_RED,               OGL_TYPE_I8,                    0},
            /*FORMAT_R8_USCALED_PACK8              */{OGL_INTERNAL_R8_USCALED_GTC,                   OGL_EXTERNAL_RED,               OGL_TYPE_U8,                    0},
            /*FORMAT_R8_SSCALED_PACK8              */{OGL_INTERNAL_R8_SSCALED_GTC,                   OGL_EXTERNAL_RED,               OGL_TYPE_I8,                    0},
            /*FORMAT_R8_UINT_PACK8                 */{OGL_INTERNAL_R8U,                              OGL_EXTERNAL_RED_INTEGER,       OGL_TYPE_U8,                    0},
            /*FORMAT_R8_SINT_PACK8                 */{OGL_INTERNAL_R8I,                              OGL_EXTERNAL_RED_INTEGER,       OGL_TYPE_I8,                    0},
            /*FORMAT_R8_SRGB_PACK8                 */{OGL_INTERNAL_SR8,                              OGL_EXTERNAL_RED,               OGL_TYPE_U8,                    0},

            /*FORMAT_RG8_UNORM_PACK8               */{OGL_INTERNAL_RG8_UNORM,                        OGL_EXTERNAL_RG,                OGL_TYPE_U8,                    0},
            /*FORMAT_RG8_SNORM_PACK8               */{OGL_INTERNAL_RG8_SNORM,                        OGL_EXTERNAL_RG,                OGL_TYPE_I8,                    0},
            /*FORMAT_RG8_USCALED_PACK8             */{OGL_INTERNAL_RG8_USCALED_GTC,                  OGL_EXTERNAL_RG,                OGL_TYPE_U8,                    0},
            /*FORMAT_RG8_SSCALED_PACK8             */{OGL_INTERNAL_RG8_SSCALED_GTC,                  OGL_EXTERNAL_RG,                OGL_TYPE_I8,                    0},
            /*FORMAT_RG8_UINT_PACK8                */{OGL_INTERNAL_RG8U,                             OGL_EXTERNAL_RG_INTEGER,        OGL_TYPE_U8,                    0},
            /*FORMAT_RG8_SINT_PACK8                */{OGL_INTERNAL_RG8I,                             OGL_EXTERNAL_RG_INTEGER,        OGL_TYPE_I8,                    0},
            /*FORMAT_RG8_SRGB_PACK8                */{OGL_INTERNAL_SRG8,                             OGL_EXTERNAL_RG,                OGL_TYPE_U8,                    0},

            /*FORMAT_RGB8_UNORM_PACK8              */{OGL_INTERNAL_RGB8_UNORM,                       OGL_EXTERNAL_RGB,               OGL_TYPE_U8,                    0},
            /*FORMAT_RGB8_SNORM_PACK8              */{OGL_INTERNAL_RGB8_SNORM,                       OGL_EXTERNAL_RGB,               OGL_TYPE_I8,                    0},
            /*FORMAT_RGB8_USCALED_PACK8            */{OGL_INTERNAL_RGB8_USCALED_GTC,                 OGL_EXTERNAL_RGB,               OGL_TYPE_U8,                    0},
            /*FORMAT_RGB8_SSCALED_PACK8            */{OGL_INTERNAL_RGB8_SSCALED_GTC,                 OGL_EXTERNAL_RGB,               OGL_TYPE_I8,                    0},
            /*FORMAT_RGB8_UINT_PACK8               */{OGL_INTERNAL_RGB8U,                            OGL_EXTERNAL_RGB_INTEGER,       OGL_TYPE_U8,                    0},
            /*FORMAT_RGB8_SINT_PACK8               */{OGL_INTERNAL_RGB8I,                            OGL_EXTERNAL_RGB_INTEGER,       OGL_TYPE_I8,                    0},
            /*FORMAT_RGB8_SRGB_PACK8               */{OGL_INTERNAL_SRGB8,                            ogl_external_SRGB8,             OGL_TYPE_U8,                    0},

            /*FORMAT_BGR8_UNORM_PACK8              */{OGL_INTERNAL_RGB8_UNORM,                       ogl_external_BGR,               OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGR8_SNORM_PACK8              */{OGL_INTERNAL_RGB8_SNORM,                       ogl_external_BGR,               OGL_TYPE_I8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGR8_USCALED_PACK8            */{OGL_INTERNAL_RGB8_USCALED_GTC,                 ogl_external_BGR,               OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGR8_SSCALED_PACK8            */{OGL_INTERNAL_RGB8_SSCALED_GTC,                 ogl_external_BGR,               OGL_TYPE_I8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGR8_UINT_PACK8               */{OGL_INTERNAL_RGB8U,                            ogl_external_BGRInt,            OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGR8_SINT_PACK8               */{OGL_INTERNAL_RGB8I,                            ogl_external_BGRInt,            OGL_TYPE_I8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGR8_SRGB_PACK8               */{OGL_INTERNAL_SRGB8,                            ogl_external_BGR,               OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},

            /*FORMAT_RGBA8_UNORM_PACK8             */{OGL_INTERNAL_RGBA8_UNORM,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_U8,                    0},
            /*FORMAT_RGBA8_SNORM_PACK8             */{OGL_INTERNAL_RGBA8_SNORM,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_I8,                    0},
            /*FORMAT_RGBA8_USCALED_PACK8           */{OGL_INTERNAL_RGBA8_USCALED_GTC,                OGL_EXTERNAL_RGBA,              OGL_TYPE_U8,                    0},
            /*FORMAT_RGBA8_SSCALED_PACK8           */{OGL_INTERNAL_RGBA8_SSCALED_GTC,                OGL_EXTERNAL_RGBA,              OGL_TYPE_I8,                    0},
            /*FORMAT_RGBA8_UINT_PACK8              */{OGL_INTERNAL_RGBA8U,                           OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_U8,                    0},
            /*FORMAT_RGBA8_SINT_PACK8              */{OGL_INTERNAL_RGBA8I,                           OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_I8,                    0},
            /*FORMAT_RGBA8_SRGB_PACK8              */{OGL_INTERNAL_SRGB8_ALPHA8,                     ogl_external_SRGB8_A8,          OGL_TYPE_U8,                    0},

            /*FORMAT_BGRA8_UNORM_PACK8             */{ogl_internal_BGRA,                             ogl_external_BGRA,              OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGRA8_SNORM_PACK8             */{OGL_INTERNAL_RGBA8_SNORM,                      ogl_external_BGRA,              OGL_TYPE_I8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGRA8_USCALED_PACK8           */{OGL_INTERNAL_RGBA8_USCALED_GTC,                ogl_external_BGRA,              OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGRA8_SSCALED_PACK8           */{OGL_INTERNAL_RGBA8_SSCALED_GTC,                ogl_external_BGRA,              OGL_TYPE_I8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGRA8_UINT_PACK8              */{OGL_INTERNAL_RGBA8U,                           ogl_external_BGRAInt,           OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGRA8_SINT_PACK8              */{OGL_INTERNAL_RGBA8I,                           ogl_external_BGRAInt,           OGL_TYPE_I8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},
            /*FORMAT_BGRA8_SRGB_PACK8              */{OGL_INTERNAL_SRGB8_ALPHA8,                     ogl_external_BGRA,              OGL_TYPE_U8,                    FORMAT_PROPERTY_BGRA_FORMAT_BIT},

            /*FORMAT_RGBA8_UNORM_PACK32            */{OGL_INTERNAL_RGBA8_UNORM,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGBA8_REV,      0},
            /*FORMAT_RGBA8_SNORM_PACK32            */{OGL_INTERNAL_RGBA8_SNORM,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGBA8_REV,      0},
            /*FORMAT_RGBA8_USCALED_PACK32          */{OGL_INTERNAL_RGBA8_USCALED_GTC,                OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGBA8_REV,      0},
            /*FORMAT_RGBA8_SSCALED_PACK32          */{OGL_INTERNAL_RGBA8_SSCALED_GTC,                OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGBA8_REV,      0},
            /*FORMAT_RGBA8_UINT_PACK32             */{OGL_INTERNAL_RGBA8U,                           OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_UINT32_RGBA8_REV,      0},
            /*FORMAT_RGBA8_SINT_PACK32             */{OGL_INTERNAL_RGBA8I,                           OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_UINT32_RGBA8_REV,      0},
            /*FORMAT_RGBA8_SRGB_PACK32             */{OGL_INTERNAL_SRGB8_ALPHA8,                     OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGBA8_REV,      0},

            /*FORMAT_RGB10A2_UNORM_PACK32          */{OGL_INTERNAL_RGB10A2_UNORM,                    OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2_REV,    0},
            /*FORMAT_RGB10A2_SNORM_PACK32          */{OGL_INTERNAL_RGB10A2_SNORM_EXT,                OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2_REV,    0},
            /*FORMAT_RGB10A2_USCALED_PACK32        */{OGL_INTERNAL_RGB10A2_USCALED_GTC,              OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2_REV,    0},
            /*FORMAT_RGB10A2_SSCALED_PACK32        */{OGL_INTERNAL_RGB10A2_SSCALED_GTC,              OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2_REV,    0},
            /*FORMAT_RGB10A2_UINT_PACK32           */{OGL_INTERNAL_RGB10A2U,                         OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_UINT32_RGB10A2_REV,    0},
            /*FORMAT_RGB10A2_SINT_PACK32           */{OGL_INTERNAL_RGB10A2I_EXT,                     OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_UINT32_RGB10A2_REV,    0},

            /*FORMAT_BGR10A2_UNORM_PACK32          */{OGL_INTERNAL_RGB10A2_UNORM,                    OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2,        FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_BGR10A2_SNORM_PACK32          */{OGL_INTERNAL_RGB10A2_SNORM_EXT,                OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2,        FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_BGR10A2_USCALED_PACK32        */{OGL_INTERNAL_RGB10A2_USCALED_GTC,              OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2,        FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_BGR10A2_SSCALED_PACK32        */{OGL_INTERNAL_RGB10A2_SSCALED_GTC,              OGL_EXTERNAL_RGBA,              OGL_TYPE_UINT32_RGB10A2,        FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_BGR10A2_UINT_PACK32           */{OGL_INTERNAL_RGB10A2U,                         OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_UINT32_RGB10A2,        FORMAT_PROPERTY_BGRA_TYPE_BIT},
            /*FORMAT_BGR10A2_SINT_PACK32           */{OGL_INTERNAL_RGB10A2I_EXT,                     OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_UINT32_RGB10A2,        FORMAT_PROPERTY_BGRA_TYPE_BIT},

            /*FORMAT_R16_UNORM_PACK16              */{OGL_INTERNAL_R16_UNORM,                        OGL_EXTERNAL_RED,               OGL_TYPE_U16,                   0},
            /*FORMAT_R16_SNORM_PACK16              */{OGL_INTERNAL_R16_SNORM,                        OGL_EXTERNAL_RED,               OGL_TYPE_I16,                   0},
            /*FORMAT_R16_USCALED_PACK16            */{OGL_INTERNAL_R16_USCALED_GTC,                  OGL_EXTERNAL_RED,               OGL_TYPE_U16,                   0},
            /*FORMAT_R16_SSCALED_PACK16            */{OGL_INTERNAL_R16_SSCALED_GTC,                  OGL_EXTERNAL_RED,               OGL_TYPE_I16,                   0},
            /*FORMAT_R16_UINT_PACK16               */{OGL_INTERNAL_R16U,                             OGL_EXTERNAL_RED_INTEGER,       OGL_TYPE_U16,                   0},
            /*FORMAT_R16_SINT_PACK16               */{OGL_INTERNAL_R16I,                             OGL_EXTERNAL_RED_INTEGER,       OGL_TYPE_I16,                   0},
            /*FORMAT_R16_SFLOAT_PACK16             */{OGL_INTERNAL_R16F,                             OGL_EXTERNAL_RED,               ogl_type_F16,                   0},

            /*FORMAT_RG16_UNORM_PACK16             */{OGL_INTERNAL_RG16_UNORM,                       OGL_EXTERNAL_RG,                OGL_TYPE_U16,                   0},
            /*FORMAT_RG16_SNORM_PACK16             */{OGL_INTERNAL_RG16_SNORM,                       OGL_EXTERNAL_RG,                OGL_TYPE_I16,                   0},
            /*FORMAT_RG16_USCALED_PACK16           */{OGL_INTERNAL_RG16_USCALED_GTC,                 OGL_EXTERNAL_RG,                OGL_TYPE_U16,                   0},
            /*FORMAT_RG16_SSCALED_PACK16           */{OGL_INTERNAL_RG16_SSCALED_GTC,                 OGL_EXTERNAL_RG,                OGL_TYPE_I16,                   0},
            /*FORMAT_RG16_UINT_PACK16              */{OGL_INTERNAL_RG16U,                            OGL_EXTERNAL_RG_INTEGER,        OGL_TYPE_U16,                   0},
            /*FORMAT_RG16_SINT_PACK16              */{OGL_INTERNAL_RG16I,                            OGL_EXTERNAL_RG_INTEGER,        OGL_TYPE_I16,                   0},
            /*FORMAT_RG16_SFLOAT_PACK16            */{OGL_INTERNAL_RG16F,                            OGL_EXTERNAL_RG,                ogl_type_F16,                   0},

            /*FORMAT_RGB16_UNORM_PACK16            */{OGL_INTERNAL_RGB16_UNORM,                      OGL_EXTERNAL_RGB,               OGL_TYPE_U16,                   0},
            /*FORMAT_RGB16_SNORM_PACK16            */{OGL_INTERNAL_RGB16_SNORM,                      OGL_EXTERNAL_RGB,               OGL_TYPE_I16,                   0},
            /*FORMAT_RGB16_USCALED_PACK16          */{OGL_INTERNAL_RGB16_USCALED_GTC,                OGL_EXTERNAL_RGB,               OGL_TYPE_U16,                   0},
            /*FORMAT_RGB16_SSCALED_PACK16          */{OGL_INTERNAL_RGB16_SSCALED_GTC,                OGL_EXTERNAL_RGB,               OGL_TYPE_I16,                   0},
            /*FORMAT_RGB16_UINT_PACK16             */{OGL_INTERNAL_RGB16U,                           OGL_EXTERNAL_RGB_INTEGER,       OGL_TYPE_U16,                   0},
            /*FORMAT_RGB16_SINT_PACK16             */{OGL_INTERNAL_RGB16I,                           OGL_EXTERNAL_RGB_INTEGER,       OGL_TYPE_I16,                   0},
            /*FORMAT_RGB16_SFLOAT_PACK16           */{OGL_INTERNAL_RGB16F,                           OGL_EXTERNAL_RGB,               ogl_type_F16,                   0},

            /*FORMAT_RGBA16_UNORM_PACK16           */{OGL_INTERNAL_RGBA16_UNORM,                     OGL_EXTERNAL_RGBA,              OGL_TYPE_U16,                   0},
            /*FORMAT_RGBA16_SNORM_PACK16           */{OGL_INTERNAL_RGBA16_SNORM,                     OGL_EXTERNAL_RGBA,              OGL_TYPE_I16,                   0},
            /*FORMAT_RGBA16_USCALED_PACK16         */{OGL_INTERNAL_RGBA16_USCALED_GTC,               OGL_EXTERNAL_RGBA,              OGL_TYPE_U16,                   0},
            /*FORMAT_RGBA16_SSCALED_PACK16         */{OGL_INTERNAL_RGBA16_SSCALED_GTC,               OGL_EXTERNAL_RGBA,              OGL_TYPE_I16,                   0},
            /*FORMAT_RGBA16_UINT_PACK16            */{OGL_INTERNAL_RGBA16U,                          OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_U16,                   0},
            /*FORMAT_RGBA16_SINT_PACK16            */{OGL_INTERNAL_RGBA16I,                          OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_I16,                   0},
            /*FORMAT_RGBA16_SFLOAT_PACK16          */{OGL_INTERNAL_RGBA16F,                          OGL_EXTERNAL_RGBA,              ogl_type_F16,                   0},

            /*FORMAT_R32_UINT_PACK32               */{OGL_INTERNAL_R32U,                             OGL_EXTERNAL_RED_INTEGER,       OGL_TYPE_U32,                   0},
            /*FORMAT_R32_SINT_PACK32               */{OGL_INTERNAL_R32I,                             OGL_EXTERNAL_RED_INTEGER,       OGL_TYPE_I32,                   0},
            /*FORMAT_R32_SFLOAT_PACK32             */{OGL_INTERNAL_R32F,                             OGL_EXTERNAL_RED,               OGL_TYPE_F32,                   0},

            /*FORMAT_RG32_UINT_PACK32              */{OGL_INTERNAL_RG32U,                            OGL_EXTERNAL_RG_INTEGER,        OGL_TYPE_U32,                   0},
            /*FORMAT_RG32_SINT_PACK32              */{OGL_INTERNAL_RG32I,                            OGL_EXTERNAL_RG_INTEGER,        OGL_TYPE_I32,                   0},
            /*FORMAT_RG32_SFLOAT_PACK32            */{OGL_INTERNAL_RG32F,                            OGL_EXTERNAL_RG,                OGL_TYPE_F32,                   0},

            /*FORMAT_RGB32_UINT_PACK32             */{OGL_INTERNAL_RGB32U,                           OGL_EXTERNAL_RGB_INTEGER,       OGL_TYPE_U32,                   0},
            /*FORMAT_RGB32_SINT_PACK32             */{OGL_INTERNAL_RGB32I,                           OGL_EXTERNAL_RGB_INTEGER,       OGL_TYPE_I32,                   0},
            /*FORMAT_RGB32_SFLOAT_PACK32           */{OGL_INTERNAL_RGB32F,                           OGL_EXTERNAL_RGB,               OGL_TYPE_F32,                   0},

            /*FORMAT_RGBA32_UINT_PACK32            */{OGL_INTERNAL_RGBA32U,                          OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_U32,                   0},
            /*FORMAT_RGBA32_SINT_PACK32            */{OGL_INTERNAL_RGBA32I,                          OGL_EXTERNAL_RGBA_INTEGER,      OGL_TYPE_I32,                   0},
            /*FORMAT_RGBA32_SFLOAT_PACK32          */{OGL_INTERNAL_RGBA32F,                          OGL_EXTERNAL_RGBA,              OGL_TYPE_F32,                   0},

            /*FORMAT_R64_UINT_PACK64               */{OGL_INTERNAL_R64F_EXT,                         OGL_EXTERNAL_RED,               OGL_TYPE_U64,                   0},
            /*FORMAT_R64_SINT_PACK64               */{OGL_INTERNAL_R64F_EXT,                         OGL_EXTERNAL_RED,               OGL_TYPE_I64,                   0},
            /*FORMAT_R64_SFLOAT_PACK64             */{OGL_INTERNAL_R64F_EXT,                         OGL_EXTERNAL_RED,               OGL_TYPE_F64,                   0},

            /*FORMAT_RG64_UINT_PACK64              */{OGL_INTERNAL_RG64F_EXT,                        OGL_EXTERNAL_RG,                OGL_TYPE_U64,                   0},
            /*FORMAT_RG64_SINT_PACK64              */{OGL_INTERNAL_RG64F_EXT,                        OGL_EXTERNAL_RG,                OGL_TYPE_I64,                   0},
            /*FORMAT_RG64_SFLOAT_PACK64            */{OGL_INTERNAL_RG64F_EXT,                        OGL_EXTERNAL_RG,                OGL_TYPE_F64,                   0},

            /*FORMAT_RGB64_UINT_PACK64             */{OGL_INTERNAL_RGB64F_EXT,                       OGL_EXTERNAL_RGB,               OGL_TYPE_U64,                   0},
            /*FORMAT_RGB64_SINT_PACK64             */{OGL_INTERNAL_RGB64F_EXT,                       OGL_EXTERNAL_RGB,               OGL_TYPE_I64,                   0},
            /*FORMAT_RGB64_SFLOAT_PACK64           */{OGL_INTERNAL_RGB64F_EXT,                       OGL_EXTERNAL_RGB,               OGL_TYPE_F64,                   0},

            /*FORMAT_RGBA64_UINT_PACK64            */{OGL_INTERNAL_RGBA64F_EXT,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_U64,                   0},
            /*FORMAT_RGBA64_SINT_PACK64            */{OGL_INTERNAL_RGBA64F_EXT,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_I64,                   0},
            /*FORMAT_RGBA64_SFLOAT_PACK64          */{OGL_INTERNAL_RGBA64F_EXT,                      OGL_EXTERNAL_RGBA,              OGL_TYPE_F64,                   0},

            /*FORMAT_RG11B10_UFLOAT_PACK32         */{OGL_INTERNAL_RG11B10F,                         OGL_EXTERNAL_RGB,               OGL_TYPE_UINT32_RG11B10F_REV,   0},
            /*FORMAT_RGB9E5_UFLOAT_PACK32          */{OGL_INTERNAL_RGB9E5,                           OGL_EXTERNAL_RGB,               OGL_TYPE_UINT32_RGB9_E5_REV,    0},

            /*FORMAT_D16_UNORM_PACK16              */{OGL_INTERNAL_D16,                              OGL_EXTERNAL_DEPTH,             OGL_TYPE_NONE,                  0},
            /*FORMAT_D24_UNORM_PACK32              */{OGL_INTERNAL_D24,                              OGL_EXTERNAL_DEPTH,             OGL_TYPE_NONE,                  0},
            /*FORMAT_D32_SFLOAT_PACK32             */{OGL_INTERNAL_D32F,                             OGL_EXTERNAL_DEPTH,             OGL_TYPE_NONE,                  0},
            /*FORMAT_S8_UINT_PACK8                 */{OGL_INTERNAL_S8_EXT,                           OGL_EXTERNAL_STENCIL,           OGL_TYPE_NONE,                  0},
            /*FORMAT_D16_UNORM_S8_UINT_PACK32      */{OGL_INTERNAL_D16S8_EXT,                        OGL_EXTERNAL_DEPTH,             OGL_TYPE_NONE,                  0},
            /*FORMAT_D24_UNORM_S8_UINT_PACK32      */{OGL_INTERNAL_D24S8,                            OGL_EXTERNAL_DEPTH_STENCIL,     OGL_TYPE_NONE,                  0},
            /*FORMAT_D32_SFLOAT_S8_UINT_PACK64     */{OGL_INTERNAL_D32FS8X24,                        OGL_EXTERNAL_DEPTH_STENCIL,     OGL_TYPE_NONE,                  0},

            /*FORMAT_RGB_DXT1_UNORM_BLOCK8         */{OGL_INTERNAL_RGB_DXT1,                         OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_DXT1_SRGB_BLOCK8          */{OGL_INTERNAL_SRGB_DXT1,                        OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_DXT1_UNORM_BLOCK8        */{OGL_INTERNAL_RGBA_DXT1,                        OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_DXT1_SRGB_BLOCK8         */{OGL_INTERNAL_SRGB_ALPHA_DXT1,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_DXT3_UNORM_BLOCK16       */{OGL_INTERNAL_RGBA_DXT3,                        OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_DXT3_SRGB_BLOCK16        */{OGL_INTERNAL_SRGB_ALPHA_DXT3,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_DXT5_UNORM_BLOCK16       */{OGL_INTERNAL_RGBA_DXT5,                        OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_DXT5_SRGB_BLOCK16        */{OGL_INTERNAL_SRGB_ALPHA_DXT5,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_R_ATI1N_UNORM_BLOCK8          */{OGL_INTERNAL_R_ATI1N_UNORM,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_R_ATI1N_SNORM_BLOCK8          */{OGL_INTERNAL_R_ATI1N_SNORM,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RG_ATI2N_UNORM_BLOCK16        */{OGL_INTERNAL_RG_ATI2N_UNORM,                   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RG_ATI2N_SNORM_BLOCK16        */{OGL_INTERNAL_RG_ATI2N_SNORM,                   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_BP_UFLOAT_BLOCK16         */{OGL_INTERNAL_RGB_BP_UNSIGNED_FLOAT,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_BP_SFLOAT_BLOCK16         */{OGL_INTERNAL_RGB_BP_SIGNED_FLOAT,              OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_BP_UNORM_BLOCK16         */{OGL_INTERNAL_RGB_BP_UNORM,                     OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_BP_SRGB_BLOCK16          */{OGL_INTERNAL_SRGB_BP_UNORM,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},

            /*FORMAT_RGB_ETC2_UNORM_BLOCK8         */{ogl_internal_RGBETC,                           OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_ETC2_SRGB_BLOCK8          */{OGL_INTERNAL_SRGB8_ETC2,                       OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ETC2_UNORM_BLOCK8        */{OGL_INTERNAL_RGBA_PUNCHTHROUGH_ETC2,           OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ETC2_SRGB_BLOCK8         */{OGL_INTERNAL_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ETC2_UNORM_BLOCK16       */{OGL_INTERNAL_RGBA_ETC2,                        OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ETC2_SRGB_BLOCK16        */{OGL_INTERNAL_SRGB8_ALPHA8_ETC2_EAC,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_R_EAC_UNORM_BLOCK8            */{OGL_INTERNAL_R11_EAC,                          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_R_EAC_SNORM_BLOCK8            */{OGL_INTERNAL_SIGNED_R11_EAC,                   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RG_EAC_UNORM_BLOCK16          */{OGL_INTERNAL_RG11_EAC,                         OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RG_EAC_SNORM_BLOCK16          */{OGL_INTERNAL_SIGNED_RG11_EAC,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},

            /*FORMAT_RGBA_ASTC_4X4_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_4x4,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_4X4_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_4x4,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_5X4_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_5x4,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_5X4_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_5x4,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_5X5_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_5x5,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_5X5_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_5x5,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_6X5_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_6x5,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_6X5_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_6x5,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_6X6_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_6x6,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_6X6_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_6x6,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_8X5_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_8x5,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_8X5_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_8x5,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_8X6_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_8x6,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_8X6_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_8x6,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_8X8_UNORM_BLOCK16   */{OGL_INTERNAL_RGBA_ASTC_8x8,                    OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_8X8_SRGB_BLOCK16    */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_8x8,            OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X5_UNORM_BLOCK16  */{OGL_INTERNAL_RGBA_ASTC_10x5,                   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X5_SRGB_BLOCK16   */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_10x5,           OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X6_UNORM_BLOCK16  */{OGL_INTERNAL_RGBA_ASTC_10x6,                   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X6_SRGB_BLOCK16   */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_10x6,           OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X8_UNORM_BLOCK16  */{OGL_INTERNAL_RGBA_ASTC_10x8,                   OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X8_SRGB_BLOCK16   */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_10x8,           OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X10_UNORM_BLOCK16 */{OGL_INTERNAL_RGBA_ASTC_10x10,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_10X10_SRGB_BLOCK16  */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_10x10,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_12X10_UNORM_BLOCK16 */{OGL_INTERNAL_RGBA_ASTC_12x10,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_12X10_SRGB_BLOCK16  */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_12x10,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_12X12_UNORM_BLOCK16 */{OGL_INTERNAL_RGBA_ASTC_12x12,                  OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ASTC_12X12_SRGB_BLOCK16  */{OGL_INTERNAL_SRGB8_ALPHA8_ASTC_12x12,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},

            /*FORMAT_RGB_PVRTC1_8X8_UNORM_BLOCK32  */{OGL_INTERNAL_RGB_PVRTC_4BPPV1,                 OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_PVRTC1_8X8_SRGB_BLOCK32   */{OGL_INTERNAL_SRGB_PVRTC_2BPPV1,                OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_PVRTC1_16X8_UNORM_BLOCK32 */{OGL_INTERNAL_RGB_PVRTC_2BPPV1,                 OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_PVRTC1_16X8_SRGB_BLOCK32  */{OGL_INTERNAL_SRGB_PVRTC_4BPPV1,                OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC1_8X8_UNORM_BLOCK32 */{OGL_INTERNAL_RGBA_PVRTC_4BPPV1,                OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC1_8X8_SRGB_BLOCK32  */{OGL_INTERNAL_SRGB_ALPHA_PVRTC_2BPPV1,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC1_16X8_UNORM_BLOCK32*/{OGL_INTERNAL_RGBA_PVRTC_2BPPV1,                OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC1_16X8_SRGB_BLOCK32 */{OGL_INTERNAL_SRGB_ALPHA_PVRTC_4BPPV1,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC2_4X4_UNORM_BLOCK8  */{OGL_INTERNAL_RGBA_PVRTC_4BPPV2,                OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC2_4X4_SRGB_BLOCK8   */{OGL_INTERNAL_SRGB_ALPHA_PVRTC_4BPPV2,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC2_8X4_UNORM_BLOCK8  */{OGL_INTERNAL_RGBA_PVRTC_2BPPV2,                OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_PVRTC2_8X4_SRGB_BLOCK8   */{OGL_INTERNAL_SRGB_ALPHA_PVRTC_2BPPV2,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},

            /*FORMAT_RGB_ETC_UNORM_BLOCK8          */{OGL_INTERNAL_RGB_ETC,                          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGB_ATC_UNORM_BLOCK8          */{OGL_INTERNAL_ATC_RGB,                          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ATCA_UNORM_BLOCK16       */{OGL_INTERNAL_ATC_RGBA_EXPLICIT_ALPHA,          OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},
            /*FORMAT_RGBA_ATCI_UNORM_BLOCK16       */{OGL_INTERNAL_ATC_RGBA_INTERPOLATED_ALPHA,      OGL_EXTERNAL_NONE,              OGL_TYPE_NONE,                  0},

            /*FORMAT_L8_UNORM_PACK8                */{ogl_internal_Luminance8,                       ogl_external_Luminance,         OGL_TYPE_U8,                    0},
            /*FORMAT_A8_UNORM_PACK8                */{ogl_internal_Alpha8,                           ogl_external_Alpha,             OGL_TYPE_U8,                    0},
            /*FORMAT_LA8_UNORM_PACK8               */{ogl_internal_LuminanceAlpha8,                  ogl_external_LuminanceAlpha,    OGL_TYPE_U8,                    0},
            /*FORMAT_L16_UNORM_PACK16              */{ogl_internal_Luminance16,                      ogl_external_Luminance,         OGL_TYPE_U16,                   0},
            /*FORMAT_A16_UNORM_PACK16              */{ogl_internal_Alpha16,                          ogl_external_Alpha,             OGL_TYPE_U16,                   0},
            /*FORMAT_LA16_UNORM_PACK16             */{ogl_internal_LuminanceAlpha16,                 ogl_external_LuminanceAlpha,    OGL_TYPE_U16,                   0},

            /*FORMAT_BGR8_UNORM_PACK32             */{OGL_INTERNAL_RGB8_UNORM,                       ogl_external_BGRA,              OGL_TYPE_U8,                    0},
            /*FORMAT_BGR8_SRGB_PACK32              */{OGL_INTERNAL_SRGB8,                            ogl_external_BGRA,              OGL_TYPE_U8,                    0},

            /*FORMAT_RG3B2_UNORM_PACK8             */{OGL_INTERNAL_RG3B2,                            OGL_EXTERNAL_RGB,               OGL_TYPE_UINT8_RG3B2_REV,       0},
        };

        _formatDesc.resize(FORMAT_COUNT);

        std::copy(&formatDesc[0], &formatDesc[0] + FORMAT_COUNT, _formatDesc.begin());
    }
}

ImageFormat::Format ImageFormat::find(GlInternalFormat internalFormat, GlExternalFormat externalFormat, GlTypeFormat type)
{
    std::size_t sz = _formatDesc.size();

    for (std::size_t idx = 0; idx <= sz; ++idx)
    {
        if (_formatDesc[idx].internalFormat != internalFormat) continue;
        if (_formatDesc[idx].externalFormat != externalFormat) continue;
        if (_formatDesc[idx].type           != type)           continue;

        return static_cast<Format>(idx);
    }

    return FORMAT_UNDEFINED;
}

OSG_END_NAMESPACE
