/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGDESCMATERIALFACTORYFIELDS_H_
#define _OSGDESCMATERIALFACTORYFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class DescMaterialFactory;

OSG_GEN_CONTAINERPTR(DescMaterialFactory);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<DescMaterialFactory *, nsOSG> :
    public FieldTraitsFCPtrBase<DescMaterialFactory *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<DescMaterialFactory *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakDescMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<DescMaterialFactory *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdDescMaterialFactoryPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialFactory *,
                      RecordedRefCountPolicy, nsOSG  > SFRecDescMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialFactory *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecDescMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialFactory *,
                      WeakRefCountPolicy, nsOSG      > SFWeakDescMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<DescMaterialFactory *,
                      NoRefCountPolicy, nsOSG        > SFUncountedDescMaterialFactoryPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialFactory *,
                      RecordedRefCountPolicy, nsOSG  > MFRecDescMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialFactory *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecDescMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialFactory *,
                      WeakRefCountPolicy, nsOSG      > MFWeakDescMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<DescMaterialFactory *,
                      NoRefCountPolicy, nsOSG        > MFUncountedDescMaterialFactoryPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecDescMaterialFactoryPtr : 
    public PointerSField<DescMaterialFactory *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecDescMaterialFactoryPtr : 
    public PointerSField<DescMaterialFactory *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakDescMaterialFactoryPtr :
    public PointerSField<DescMaterialFactory *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedDescMaterialFactoryPtr :
    public PointerSField<DescMaterialFactory *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecDescMaterialFactoryPtr :
    public PointerMField<DescMaterialFactory *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecDescMaterialFactoryPtr :
    public PointerMField<DescMaterialFactory *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakDescMaterialFactoryPtr :
    public PointerMField<DescMaterialFactory *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedDescMaterialFactoryPtr :
    public PointerMField<DescMaterialFactory *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGDESCMATERIALFACTORYFIELDS_H_ */
