/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMATERIALFACTORYFIELDS_H_
#define _OSGMATERIALFACTORYFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MaterialFactory;

OSG_GEN_CONTAINERPTR(MaterialFactory);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<MaterialFactory *, nsOSG> :
    public FieldTraitsFCPtrBase<MaterialFactory *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MaterialFactory *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMaterialFactoryPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialFactory *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMaterialFactoryPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MaterialFactory *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MaterialFactory *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MaterialFactory *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<MaterialFactory *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMaterialFactoryPtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MaterialFactory *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MaterialFactory *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MaterialFactory *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMaterialFactoryPtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<MaterialFactory *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMaterialFactoryPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecMaterialFactoryPtr : 
    public PointerSField<MaterialFactory *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecMaterialFactoryPtr : 
    public PointerSField<MaterialFactory *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakMaterialFactoryPtr :
    public PointerSField<MaterialFactory *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedMaterialFactoryPtr :
    public PointerSField<MaterialFactory *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecMaterialFactoryPtr :
    public PointerMField<MaterialFactory *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecMaterialFactoryPtr :
    public PointerMField<MaterialFactory *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakMaterialFactoryPtr :
    public PointerMField<MaterialFactory *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedMaterialFactoryPtr :
    public PointerMField<MaterialFactory *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMATERIALFACTORYFIELDS_H_ */
