/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class GeoVectorBufferRefProperty!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"




#include "OSGGeoVectorBufferRefPropertyBase.h"
#include "OSGGeoVectorBufferRefProperty.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::GeoVectorBufferRefProperty
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var UInt32          GeoVectorBufferRefPropertyBase::_sfOsgGLId
    The OpenSG GL object id for this geo property buffer object. If osgGLId is set, the GL object id
    is determined by OpenSG. If osgGLId equals 0, the GLId is used directly as the GL object id.
    An API getOglGLId()/setOglGLId() is provided to get/set the inherited GLId. This brings the
    interface more in line to the TextureObjRefChunk and the ShaderStorageBufferRefObjChunk
    classes.
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<GeoVectorBufferRefProperty *, nsOSG>::_type(
    "GeoVectorBufferRefPropertyPtr", 
    "GeoVectorBufferPropertyPtr", 
    GeoVectorBufferRefProperty::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(GeoVectorBufferRefProperty *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           GeoVectorBufferRefProperty *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           GeoVectorBufferRefProperty *,
                           nsOSG)

DataType &FieldTraits< GeoVectorBufferRefProperty *, nsOSG + 1 >::getType(void)
{
    return FieldTraits<GeoVectorBufferRefProperty *, nsOSG>::getType();
}


OSG_EXPORT_PTR_SFIELD(ChildPointerSField,
                      GeoVectorBufferRefProperty *,
                      UnrecordedRefCountPolicy,
                      nsOSG + 1)


OSG_EXPORT_PTR_MFIELD(ChildPointerMField,
                      GeoVectorBufferRefProperty *,
                      UnrecordedRefCountPolicy,
                      nsOSG + 1)


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void GeoVectorBufferRefPropertyBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUInt32::Description(
        SFUInt32::getClassType(),
        "osgGLId",
        "The OpenSG GL object id for this geo property buffer object. If osgGLId is set, the GL object id\n"
        "is determined by OpenSG. If osgGLId equals 0, the GLId is used directly as the GL object id.\n"
        "An API getOglGLId()/setOglGLId() is provided to get/set the inherited GLId. This brings the\n"
        "interface more in line to the TextureObjRefChunk and the ShaderStorageBufferRefObjChunk\n"
        "classes.\n",
        OsgGLIdFieldId, OsgGLIdFieldMask,
        true,
        (Field::FClusterLocal),
        static_cast<FieldEditMethodSig>(&GeoVectorBufferRefProperty::editHandleOsgGLId),
        static_cast<FieldGetMethodSig >(&GeoVectorBufferRefProperty::getHandleOsgGLId));

    oType.addInitialDesc(pDesc);
}


GeoVectorBufferRefPropertyBase::TypeObject GeoVectorBufferRefPropertyBase::_type(
    GeoVectorBufferRefPropertyBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&GeoVectorBufferRefPropertyBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&GeoVectorBufferRefProperty::initMethod),
    reinterpret_cast<ExitContainerF>(&GeoVectorBufferRefProperty::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&GeoVectorBufferRefProperty::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"GeoVectorBufferRefProperty\"\n"
    "   parent=\"GeoVectorBufferProperty\"\n"
    "   library=\"Drawable\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   structure=\"concrete\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   decoratable=\"false\"\n"
    "   childFields=\"both\"\n"
    "   docGroupBase=\"GrpDrawablesGeometry\"\n"
    "   >\n"
    "\n"
    "    <Field\n"
    "        name=\"osgGLId\"\n"
    "        type=\"UInt32\"\n"
    "        cardinality=\"single\"\n"
    "        visibility=\"internal\"\n"
    "        access=\"public\"\n"
    "        defaultValue=\"0\"\n"
    "        fieldFlags=\"FClusterLocal\"\n"
    "\t>\n"
    "            The OpenSG GL object id for this geo property buffer object. If osgGLId is set, the GL object id\n"
    "            is determined by OpenSG. If osgGLId equals 0, the GLId is used directly as the GL object id.\n"
    "            An API getOglGLId()/setOglGLId() is provided to get/set the inherited GLId. This brings the\n"
    "            interface more in line to the TextureObjRefChunk and the ShaderStorageBufferRefObjChunk\n"
    "            classes.\n"
    "    </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &GeoVectorBufferRefPropertyBase::getType(void)
{
    return _type;
}

const FieldContainerType &GeoVectorBufferRefPropertyBase::getType(void) const
{
    return _type;
}

UInt32 GeoVectorBufferRefPropertyBase::getContainerSize(void) const
{
    return sizeof(GeoVectorBufferRefProperty);
}

/*------------------------- decorator get ------------------------------*/


SFUInt32 *GeoVectorBufferRefPropertyBase::editSFOsgGLId(void)
{
    editSField(OsgGLIdFieldMask);

    return &_sfOsgGLId;
}

const SFUInt32 *GeoVectorBufferRefPropertyBase::getSFOsgGLId(void) const
{
    return &_sfOsgGLId;
}






/*------------------------------ access -----------------------------------*/

SizeT GeoVectorBufferRefPropertyBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (OsgGLIdFieldMask & whichField))
    {
        returnValue += _sfOsgGLId.getBinSize();
    }

    return returnValue;
}

void GeoVectorBufferRefPropertyBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (OsgGLIdFieldMask & whichField))
    {
        _sfOsgGLId.copyToBin(pMem);
    }
}

void GeoVectorBufferRefPropertyBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (OsgGLIdFieldMask & whichField))
    {
        editSField(OsgGLIdFieldMask);
        _sfOsgGLId.copyFromBin(pMem);
    }
}

//! create a new instance of the class
GeoVectorBufferRefPropertyTransitPtr GeoVectorBufferRefPropertyBase::createLocal(BitVector bFlags)
{
    GeoVectorBufferRefPropertyTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<GeoVectorBufferRefProperty>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
GeoVectorBufferRefPropertyTransitPtr GeoVectorBufferRefPropertyBase::createDependent(BitVector bFlags)
{
    GeoVectorBufferRefPropertyTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<GeoVectorBufferRefProperty>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
GeoVectorBufferRefPropertyTransitPtr GeoVectorBufferRefPropertyBase::create(void)
{
    GeoVectorBufferRefPropertyTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<GeoVectorBufferRefProperty>(tmpPtr);
    }

    return fc;
}

GeoVectorBufferRefProperty *GeoVectorBufferRefPropertyBase::createEmptyLocal(BitVector bFlags)
{
    GeoVectorBufferRefProperty *returnValue;

    newPtr<GeoVectorBufferRefProperty>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
GeoVectorBufferRefProperty *GeoVectorBufferRefPropertyBase::createEmpty(void)
{
    GeoVectorBufferRefProperty *returnValue;

    newPtr<GeoVectorBufferRefProperty>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr GeoVectorBufferRefPropertyBase::shallowCopyLocal(
    BitVector bFlags) const
{
    GeoVectorBufferRefProperty *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const GeoVectorBufferRefProperty *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr GeoVectorBufferRefPropertyBase::shallowCopyDependent(
    BitVector bFlags) const
{
    GeoVectorBufferRefProperty *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const GeoVectorBufferRefProperty *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr GeoVectorBufferRefPropertyBase::shallowCopy(void) const
{
    GeoVectorBufferRefProperty *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const GeoVectorBufferRefProperty *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

GeoVectorBufferRefPropertyBase::GeoVectorBufferRefPropertyBase(void) :
    Inherited(),
    _sfOsgGLId                (UInt32(0))
{
}

GeoVectorBufferRefPropertyBase::GeoVectorBufferRefPropertyBase(const GeoVectorBufferRefPropertyBase &source) :
    Inherited(source),
    _sfOsgGLId                (source._sfOsgGLId                )
{
}


/*-------------------------- destructors ----------------------------------*/

GeoVectorBufferRefPropertyBase::~GeoVectorBufferRefPropertyBase(void)
{
}


GetFieldHandlePtr GeoVectorBufferRefPropertyBase::getHandleOsgGLId         (void) const
{
    SFUInt32::GetHandlePtr returnValue(
        new  SFUInt32::GetHandle(
             &_sfOsgGLId,
             this->getType().getFieldDesc(OsgGLIdFieldId),
             const_cast<GeoVectorBufferRefPropertyBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr GeoVectorBufferRefPropertyBase::editHandleOsgGLId        (void)
{
    SFUInt32::EditHandlePtr returnValue(
        new  SFUInt32::EditHandle(
             &_sfOsgGLId,
             this->getType().getFieldDesc(OsgGLIdFieldId),
             this));


    editSField(OsgGLIdFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void GeoVectorBufferRefPropertyBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    GeoVectorBufferRefProperty *pThis = static_cast<GeoVectorBufferRefProperty *>(this);

    pThis->execSync(static_cast<GeoVectorBufferRefProperty *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *GeoVectorBufferRefPropertyBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    GeoVectorBufferRefProperty *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const GeoVectorBufferRefProperty *>(pRefAspect),
                  dynamic_cast<const GeoVectorBufferRefProperty *>(this));

    return returnValue;
}
#endif

void GeoVectorBufferRefPropertyBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
