/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMATERIALMANAGERFIELDS_H_
#define _OSGMATERIALMANAGERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MaterialManager;

OSG_GEN_CONTAINERPTR(MaterialManager);
/*! \ingroup GrpSystemMaterialFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<MaterialManager *, nsOSG> :
    public FieldTraitsFCPtrBase<MaterialManager *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MaterialManager *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMaterialManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialManager *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMaterialManagerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialManager *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMaterialManagerPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialManager *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMaterialManagerPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialManager *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMaterialManagerPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialManager *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMaterialManagerPtr;


/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialManager *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMaterialManagerPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialManager *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMaterialManagerPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialManager *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMaterialManagerPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialManager *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMaterialManagerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecMaterialManagerPtr : 
    public PointerSField<MaterialManager *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecMaterialManagerPtr : 
    public PointerSField<MaterialManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakMaterialManagerPtr :
    public PointerSField<MaterialManager *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedMaterialManagerPtr :
    public PointerSField<MaterialManager *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecMaterialManagerPtr :
    public PointerMField<MaterialManager *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecMaterialManagerPtr :
    public PointerMField<MaterialManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakMaterialManagerPtr :
    public PointerMField<MaterialManager *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedMaterialManagerPtr :
    public PointerMField<MaterialManager *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMATERIALMANAGERFIELDS_H_ */
