/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGMATERIALDESCFIELDS_H_
#define _OSGMATERIALDESCFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class MaterialDesc;

OSG_GEN_CONTAINERPTR(MaterialDesc);
/*! \ingroup GrpSystemMaterialFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<MaterialDesc *, nsOSG> :
    public FieldTraitsFCPtrBase<MaterialDesc *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<MaterialDesc *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMaterialDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<MaterialDesc *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMaterialDescPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialDesc *,
                      RecordedRefCountPolicy, nsOSG  > SFRecMaterialDescPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialDesc *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecMaterialDescPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialDesc *,
                      WeakRefCountPolicy, nsOSG      > SFWeakMaterialDescPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<MaterialDesc *,
                      NoRefCountPolicy, nsOSG        > SFUncountedMaterialDescPtr;


/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialDesc *,
                      RecordedRefCountPolicy, nsOSG  > MFRecMaterialDescPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialDesc *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecMaterialDescPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialDesc *,
                      WeakRefCountPolicy, nsOSG      > MFWeakMaterialDescPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<MaterialDesc *,
                      NoRefCountPolicy, nsOSG        > MFUncountedMaterialDescPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecMaterialDescPtr : 
    public PointerSField<MaterialDesc *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecMaterialDescPtr : 
    public PointerSField<MaterialDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakMaterialDescPtr :
    public PointerSField<MaterialDesc *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedMaterialDescPtr :
    public PointerSField<MaterialDesc *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecMaterialDescPtr :
    public PointerMField<MaterialDesc *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecMaterialDescPtr :
    public PointerMField<MaterialDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakMaterialDescPtr :
    public PointerMField<MaterialDesc *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedMaterialDescPtr :
    public PointerMField<MaterialDesc *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGMATERIALDESCFIELDS_H_ */
