/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTEXTUREDESCFIELDS_H_
#define _OSGTEXTUREDESCFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class TextureDesc;

OSG_GEN_CONTAINERPTR(TextureDesc);
/*! \ingroup GrpSystemMaterialFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<TextureDesc *, nsOSG> :
    public FieldTraitsFCPtrBase<TextureDesc *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<TextureDesc *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTextureDescPtr"; 
}

template<> inline
const Char8 *FieldTraits<TextureDesc *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTextureDescPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<TextureDesc *,
                      RecordedRefCountPolicy, nsOSG  > SFRecTextureDescPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<TextureDesc *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecTextureDescPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<TextureDesc *,
                      WeakRefCountPolicy, nsOSG      > SFWeakTextureDescPtr;
/*! \ingroup GrpSystemMaterialFieldSFields */
typedef PointerSField<TextureDesc *,
                      NoRefCountPolicy, nsOSG        > SFUncountedTextureDescPtr;


/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<TextureDesc *,
                      RecordedRefCountPolicy, nsOSG  > MFRecTextureDescPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<TextureDesc *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecTextureDescPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<TextureDesc *,
                      WeakRefCountPolicy, nsOSG      > MFWeakTextureDescPtr;
/*! \ingroup GrpSystemMaterialFieldMFields */
typedef PointerMField<TextureDesc *,
                      NoRefCountPolicy, nsOSG        > MFUncountedTextureDescPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecTextureDescPtr : 
    public PointerSField<TextureDesc *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecTextureDescPtr : 
    public PointerSField<TextureDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakTextureDescPtr :
    public PointerSField<TextureDesc *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedTextureDescPtr :
    public PointerSField<TextureDesc *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecTextureDescPtr :
    public PointerMField<TextureDesc *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecTextureDescPtr :
    public PointerMField<TextureDesc *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakTextureDescPtr :
    public PointerMField<TextureDesc *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemMaterialFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedTextureDescPtr :
    public PointerMField<TextureDesc *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTEXTUREDESCFIELDS_H_ */
