/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGHASHKEYVALUEFIELDS_H_
#define _OSGHASHKEYVALUEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class HashKeyValue;

OSG_GEN_CONTAINERPTR(HashKeyValue);
/*! \ingroup GrpBaseFieldContainerFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<HashKeyValue *, nsOSG> :
    public FieldTraitsFCPtrBase<HashKeyValue *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<HashKeyValue *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakHashKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyValue *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdHashKeyValuePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyValue *,
                      RecordedRefCountPolicy, nsOSG  > SFRecHashKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyValue *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecHashKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyValue *,
                      WeakRefCountPolicy, nsOSG      > SFWeakHashKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyValue *,
                      NoRefCountPolicy, nsOSG        > SFUncountedHashKeyValuePtr;


/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyValue *,
                      RecordedRefCountPolicy, nsOSG  > MFRecHashKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyValue *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecHashKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyValue *,
                      WeakRefCountPolicy, nsOSG      > MFWeakHashKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyValue *,
                      NoRefCountPolicy, nsOSG        > MFUncountedHashKeyValuePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFRecHashKeyValuePtr : 
    public PointerSField<HashKeyValue *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecHashKeyValuePtr : 
    public PointerSField<HashKeyValue *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakHashKeyValuePtr :
    public PointerSField<HashKeyValue *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedHashKeyValuePtr :
    public PointerSField<HashKeyValue *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFRecHashKeyValuePtr :
    public PointerMField<HashKeyValue *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUnrecHashKeyValuePtr :
    public PointerMField<HashKeyValue *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFWeakHashKeyValuePtr :
    public PointerMField<HashKeyValue *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUncountedHashKeyValuePtr :
    public PointerMField<HashKeyValue *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGHASHKEYVALUEFIELDS_H_ */
