/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class HashKeyToFieldContainerMap!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>

#ifdef WIN32 
#pragma warning(disable: 4355) // turn off 'this' : used in base member initializer list warning
#pragma warning(disable: 4290) // disable exception specification warning
#endif

#include "OSGConfig.h"



#include "OSGHashKeyValue.h"            // Values Class

#include "OSGHashKeyToFieldContainerMapBase.h"
#include "OSGHashKeyToFieldContainerMap.h"

#include <boost/bind.hpp>

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::HashKeyToFieldContainerMap
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var HashKeyValue *  HashKeyToFieldContainerMapBase::_mfValues
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
PointerType FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::_type(
    "HashKeyToFieldContainerMapPtr", 
    "FieldContainerPtr", 
    HashKeyToFieldContainerMap::getClassType(),
    nsOSG);
#endif

OSG_FIELDTRAITS_GETTYPE_NS(HashKeyToFieldContainerMap *, nsOSG)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           HashKeyToFieldContainerMap *,
                           nsOSG)

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           HashKeyToFieldContainerMap *,
                           nsOSG)

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void HashKeyToFieldContainerMapBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new MFUnrecHashKeyValuePtr::Description(
        MFUnrecHashKeyValuePtr::getClassType(),
        "values",
        "",
        ValuesFieldId, ValuesFieldMask,
        false,
        (Field::MFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&HashKeyToFieldContainerMap::editHandleValues),
        static_cast<FieldGetMethodSig >(&HashKeyToFieldContainerMap::getHandleValues));

    oType.addInitialDesc(pDesc);
}


HashKeyToFieldContainerMapBase::TypeObject HashKeyToFieldContainerMapBase::_type(
    HashKeyToFieldContainerMapBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    nsOSG, //Namespace
    reinterpret_cast<PrototypeCreateF>(&HashKeyToFieldContainerMapBase::createEmptyLocal),
    reinterpret_cast<InitContainerF>(&HashKeyToFieldContainerMap::initMethod),
    reinterpret_cast<ExitContainerF>(&HashKeyToFieldContainerMap::exitMethod),
    reinterpret_cast<InitalInsertDescFunc>(
        reinterpret_cast<void *>(&HashKeyToFieldContainerMap::classDescInserter)),
    false,
    0,
    "<?xml version=\"1.0\" ?>\n"
    "\n"
    "<FieldContainer\n"
    "   name=\"HashKeyToFieldContainerMap\"\n"
    "   parent=\"FieldContainer\"\n"
    "   library=\"Base\"\n"
    "   structure=\"concrete\"\n"
    "   pointerfieldtypes=\"both\"\n"
    "   systemcomponent=\"true\"\n"
    "   parentsystemcomponent=\"true\"\n"
    "   childFields=\"none\"\n"
    "   docGroupBase=\"GrpBaseFieldContainer\"\n"
    ">\n"
    "  <Field\n"
    "\t name=\"values\"\n"
    "\t type=\"HashKeyValuePtr\"\n"
    "\t cardinality=\"multi\"\n"
    "\t visibility=\"external\"\n"
    "\t access=\"protected\"\n"
    "\t >\n"
    "  </Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &HashKeyToFieldContainerMapBase::getType(void)
{
    return _type;
}

const FieldContainerType &HashKeyToFieldContainerMapBase::getType(void) const
{
    return _type;
}

UInt32 HashKeyToFieldContainerMapBase::getContainerSize(void) const
{
    return sizeof(HashKeyToFieldContainerMap);
}

/*------------------------- decorator get ------------------------------*/


//! Get the HashKeyToFieldContainerMap::_mfValues field.
const MFUnrecHashKeyValuePtr *HashKeyToFieldContainerMapBase::getMFValues(void) const
{
    return &_mfValues;
}

MFUnrecHashKeyValuePtr *HashKeyToFieldContainerMapBase::editMFValues         (void)
{
    editMField(ValuesFieldMask, _mfValues);

    return &_mfValues;
}
HashKeyValue * HashKeyToFieldContainerMapBase::getValues(const UInt32 index) const
{
    return _mfValues[index];
}



void HashKeyToFieldContainerMapBase::pushToValues(HashKeyValue * const value)
{
    editMField(ValuesFieldMask, _mfValues);

    _mfValues.push_back(value);
}

void HashKeyToFieldContainerMapBase::assignValues   (const MFUnrecHashKeyValuePtr &value)
{
    MFUnrecHashKeyValuePtr::const_iterator elemIt  =
        value.begin();
    MFUnrecHashKeyValuePtr::const_iterator elemEnd =
        value.end  ();

    static_cast<HashKeyToFieldContainerMap *>(this)->clearValues();

    while(elemIt != elemEnd)
    {
        this->pushToValues(*elemIt);

        ++elemIt;
    }
}

void HashKeyToFieldContainerMapBase::removeFromValues(UInt32 uiIndex)
{
    if(uiIndex < _mfValues.size())
    {
        editMField(ValuesFieldMask, _mfValues);

        _mfValues.erase(uiIndex);
    }
}

void HashKeyToFieldContainerMapBase::removeObjFromValues(HashKeyValue * const value)
{
    Int32 iElemIdx = _mfValues.findIndex(value);

    if(iElemIdx != -1)
    {
        editMField(ValuesFieldMask, _mfValues);

        _mfValues.erase(iElemIdx);
    }
}
void HashKeyToFieldContainerMapBase::clearValues(void)
{
    editMField(ValuesFieldMask, _mfValues);


    _mfValues.clear();
}



/*------------------------------ access -----------------------------------*/

SizeT HashKeyToFieldContainerMapBase::getBinSize(ConstFieldMaskArg whichField)
{
    SizeT returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ValuesFieldMask & whichField))
    {
        returnValue += _mfValues.getBinSize();
    }

    return returnValue;
}

void HashKeyToFieldContainerMapBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ValuesFieldMask & whichField))
    {
        _mfValues.copyToBin(pMem);
    }
}

void HashKeyToFieldContainerMapBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ValuesFieldMask & whichField))
    {
        editMField(ValuesFieldMask, _mfValues);
        _mfValues.copyFromBin(pMem);
    }
}

//! create a new instance of the class
HashKeyToFieldContainerMapTransitPtr HashKeyToFieldContainerMapBase::createLocal(BitVector bFlags)
{
    HashKeyToFieldContainerMapTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<HashKeyToFieldContainerMap>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
HashKeyToFieldContainerMapTransitPtr HashKeyToFieldContainerMapBase::createDependent(BitVector bFlags)
{
    HashKeyToFieldContainerMapTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<HashKeyToFieldContainerMap>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
HashKeyToFieldContainerMapTransitPtr HashKeyToFieldContainerMapBase::create(void)
{
    HashKeyToFieldContainerMapTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<HashKeyToFieldContainerMap>(tmpPtr);
    }

    return fc;
}

HashKeyToFieldContainerMap *HashKeyToFieldContainerMapBase::createEmptyLocal(BitVector bFlags)
{
    HashKeyToFieldContainerMap *returnValue;

    newPtr<HashKeyToFieldContainerMap>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
HashKeyToFieldContainerMap *HashKeyToFieldContainerMapBase::createEmpty(void)
{
    HashKeyToFieldContainerMap *returnValue;

    newPtr<HashKeyToFieldContainerMap>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr HashKeyToFieldContainerMapBase::shallowCopyLocal(
    BitVector bFlags) const
{
    HashKeyToFieldContainerMap *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const HashKeyToFieldContainerMap *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr HashKeyToFieldContainerMapBase::shallowCopyDependent(
    BitVector bFlags) const
{
    HashKeyToFieldContainerMap *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const HashKeyToFieldContainerMap *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr HashKeyToFieldContainerMapBase::shallowCopy(void) const
{
    HashKeyToFieldContainerMap *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const HashKeyToFieldContainerMap *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

HashKeyToFieldContainerMapBase::HashKeyToFieldContainerMapBase(void) :
    Inherited(),
    _mfValues                 ()
{
}

HashKeyToFieldContainerMapBase::HashKeyToFieldContainerMapBase(const HashKeyToFieldContainerMapBase &source) :
    Inherited(source),
    _mfValues                 ()
{
}


/*-------------------------- destructors ----------------------------------*/

HashKeyToFieldContainerMapBase::~HashKeyToFieldContainerMapBase(void)
{
}

void HashKeyToFieldContainerMapBase::onCreate(const HashKeyToFieldContainerMap *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        HashKeyToFieldContainerMap *pThis = static_cast<HashKeyToFieldContainerMap *>(this);

        MFUnrecHashKeyValuePtr::const_iterator ValuesIt  =
            source->_mfValues.begin();
        MFUnrecHashKeyValuePtr::const_iterator ValuesEnd =
            source->_mfValues.end  ();

        while(ValuesIt != ValuesEnd)
        {
            pThis->pushToValues(*ValuesIt);

            ++ValuesIt;
        }
    }
}

GetFieldHandlePtr HashKeyToFieldContainerMapBase::getHandleValues          (void) const
{
    MFUnrecHashKeyValuePtr::GetHandlePtr returnValue(
        new  MFUnrecHashKeyValuePtr::GetHandle(
             &_mfValues,
             this->getType().getFieldDesc(ValuesFieldId),
             const_cast<HashKeyToFieldContainerMapBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr HashKeyToFieldContainerMapBase::editHandleValues         (void)
{
    MFUnrecHashKeyValuePtr::EditHandlePtr returnValue(
        new  MFUnrecHashKeyValuePtr::EditHandle(
             &_mfValues,
             this->getType().getFieldDesc(ValuesFieldId),
             this));

    returnValue->setAddMethod(
        boost::bind(&HashKeyToFieldContainerMap::pushToValues,
                    static_cast<HashKeyToFieldContainerMap *>(this), _1));
    returnValue->setRemoveMethod(
        boost::bind(&HashKeyToFieldContainerMap::removeFromValues,
                    static_cast<HashKeyToFieldContainerMap *>(this), _1));
    returnValue->setRemoveObjMethod(
        boost::bind(&HashKeyToFieldContainerMap::removeObjFromValues,
                    static_cast<HashKeyToFieldContainerMap *>(this), _1));
    returnValue->setClearMethod(
        boost::bind(&HashKeyToFieldContainerMap::clearValues,
                    static_cast<HashKeyToFieldContainerMap *>(this)));

    editMField(ValuesFieldMask, _mfValues);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void HashKeyToFieldContainerMapBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    HashKeyToFieldContainerMap *pThis = static_cast<HashKeyToFieldContainerMap *>(this);

    pThis->execSync(static_cast<HashKeyToFieldContainerMap *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *HashKeyToFieldContainerMapBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    HashKeyToFieldContainerMap *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const HashKeyToFieldContainerMap *>(pRefAspect),
                  dynamic_cast<const HashKeyToFieldContainerMap *>(this));

    return returnValue;
}
#endif

void HashKeyToFieldContainerMapBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<HashKeyToFieldContainerMap *>(this)->clearValues();


}


OSG_END_NAMESPACE
