/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGHASHKEYTOFIELDCONTAINERMAPFIELDS_H_
#define _OSGHASHKEYTOFIELDCONTAINERMAPFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class HashKeyToFieldContainerMap;

OSG_GEN_CONTAINERPTR(HashKeyToFieldContainerMap);
/*! \ingroup GrpBaseFieldContainerFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<HashKeyToFieldContainerMap *, nsOSG> :
    public FieldTraitsFCPtrBase<HashKeyToFieldContainerMap *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<HashKeyToFieldContainerMap *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakHashKeyToFieldContainerMapPtr"; 
}

template<> inline
const Char8 *FieldTraits<HashKeyToFieldContainerMap *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdHashKeyToFieldContainerMapPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyToFieldContainerMap *,
                      RecordedRefCountPolicy, nsOSG  > SFRecHashKeyToFieldContainerMapPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyToFieldContainerMap *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecHashKeyToFieldContainerMapPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyToFieldContainerMap *,
                      WeakRefCountPolicy, nsOSG      > SFWeakHashKeyToFieldContainerMapPtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<HashKeyToFieldContainerMap *,
                      NoRefCountPolicy, nsOSG        > SFUncountedHashKeyToFieldContainerMapPtr;


/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyToFieldContainerMap *,
                      RecordedRefCountPolicy, nsOSG  > MFRecHashKeyToFieldContainerMapPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyToFieldContainerMap *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecHashKeyToFieldContainerMapPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyToFieldContainerMap *,
                      WeakRefCountPolicy, nsOSG      > MFWeakHashKeyToFieldContainerMapPtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<HashKeyToFieldContainerMap *,
                      NoRefCountPolicy, nsOSG        > MFUncountedHashKeyToFieldContainerMapPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFRecHashKeyToFieldContainerMapPtr : 
    public PointerSField<HashKeyToFieldContainerMap *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecHashKeyToFieldContainerMapPtr : 
    public PointerSField<HashKeyToFieldContainerMap *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakHashKeyToFieldContainerMapPtr :
    public PointerSField<HashKeyToFieldContainerMap *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedHashKeyToFieldContainerMapPtr :
    public PointerSField<HashKeyToFieldContainerMap *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFRecHashKeyToFieldContainerMapPtr :
    public PointerMField<HashKeyToFieldContainerMap *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUnrecHashKeyToFieldContainerMapPtr :
    public PointerMField<HashKeyToFieldContainerMap *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFWeakHashKeyToFieldContainerMapPtr :
    public PointerMField<HashKeyToFieldContainerMap *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUncountedHashKeyToFieldContainerMapPtr :
    public PointerMField<HashKeyToFieldContainerMap *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGHASHKEYTOFIELDCONTAINERMAPFIELDS_H_ */
