/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGKEYVALUEFIELDS_H_
#define _OSGKEYVALUEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGBaseDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class KeyValue;

OSG_GEN_CONTAINERPTR(KeyValue);
/*! \ingroup GrpBaseFieldContainerFieldTraits
    \ingroup GrpLibOSGBase
 */
template <>
struct FieldTraits<KeyValue *, nsOSG> :
    public FieldTraitsFCPtrBase<KeyValue *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<KeyValue *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_BASE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakKeyValuePtr"; 
}

template<> inline
const Char8 *FieldTraits<KeyValue *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdKeyValuePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<KeyValue *,
                      RecordedRefCountPolicy, nsOSG  > SFRecKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<KeyValue *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<KeyValue *,
                      WeakRefCountPolicy, nsOSG      > SFWeakKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldSFields */
typedef PointerSField<KeyValue *,
                      NoRefCountPolicy, nsOSG        > SFUncountedKeyValuePtr;


/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<KeyValue *,
                      RecordedRefCountPolicy, nsOSG  > MFRecKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<KeyValue *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<KeyValue *,
                      WeakRefCountPolicy, nsOSG      > MFWeakKeyValuePtr;
/*! \ingroup GrpBaseFieldContainerFieldMFields */
typedef PointerMField<KeyValue *,
                      NoRefCountPolicy, nsOSG        > MFUncountedKeyValuePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFRecKeyValuePtr : 
    public PointerSField<KeyValue *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUnrecKeyValuePtr : 
    public PointerSField<KeyValue *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFWeakKeyValuePtr :
    public PointerSField<KeyValue *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldSFields \ingroup GrpLibOSGBase */
struct SFUncountedKeyValuePtr :
    public PointerSField<KeyValue *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFRecKeyValuePtr :
    public PointerMField<KeyValue *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUnrecKeyValuePtr :
    public PointerMField<KeyValue *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFWeakKeyValuePtr :
    public PointerMField<KeyValue *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpBaseFieldContainerFieldMFields \ingroup GrpLibOSGBase */
struct MFUncountedKeyValuePtr :
    public PointerMField<KeyValue *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGKEYVALUEFIELDS_H_ */
