/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCUBETEXTUREOBJCHUNKFIELDS_H_
#define _OSGCUBETEXTUREOBJCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class CubeTextureObjChunk;

OSG_GEN_CONTAINERPTR(CubeTextureObjChunk);
/*! \ingroup GrpSystemStateFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<CubeTextureObjChunk *, nsOSG> :
    public FieldTraitsFCPtrBase<CubeTextureObjChunk *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<CubeTextureObjChunk *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCubeTextureObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<CubeTextureObjChunk *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCubeTextureObjChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<CubeTextureObjChunk *,
                      RecordedRefCountPolicy, nsOSG  > SFRecCubeTextureObjChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<CubeTextureObjChunk *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecCubeTextureObjChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<CubeTextureObjChunk *,
                      WeakRefCountPolicy, nsOSG      > SFWeakCubeTextureObjChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<CubeTextureObjChunk *,
                      NoRefCountPolicy, nsOSG        > SFUncountedCubeTextureObjChunkPtr;


/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<CubeTextureObjChunk *,
                      RecordedRefCountPolicy, nsOSG  > MFRecCubeTextureObjChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<CubeTextureObjChunk *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecCubeTextureObjChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<CubeTextureObjChunk *,
                      WeakRefCountPolicy, nsOSG      > MFWeakCubeTextureObjChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<CubeTextureObjChunk *,
                      NoRefCountPolicy, nsOSG        > MFUncountedCubeTextureObjChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecCubeTextureObjChunkPtr : 
    public PointerSField<CubeTextureObjChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecCubeTextureObjChunkPtr : 
    public PointerSField<CubeTextureObjChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakCubeTextureObjChunkPtr :
    public PointerSField<CubeTextureObjChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedCubeTextureObjChunkPtr :
    public PointerSField<CubeTextureObjChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecCubeTextureObjChunkPtr :
    public PointerMField<CubeTextureObjChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecCubeTextureObjChunkPtr :
    public PointerMField<CubeTextureObjChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakCubeTextureObjChunkPtr :
    public PointerMField<CubeTextureObjChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedCubeTextureObjChunkPtr :
    public PointerMField<CubeTextureObjChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCUBETEXTUREOBJCHUNKFIELDS_H_ */
