/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSAMPLEROBJCHUNKFIELDS_H_
#define _OSGSAMPLEROBJCHUNKFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGSystemDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class SamplerObjChunk;

OSG_GEN_CONTAINERPTR(SamplerObjChunk);
/*! \ingroup GrpSystemStateFieldTraits
    \ingroup GrpLibOSGSystem
 */
template <>
struct FieldTraits<SamplerObjChunk *, nsOSG> :
    public FieldTraitsFCPtrBase<SamplerObjChunk *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SamplerObjChunk *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_SYSTEM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSamplerObjChunkPtr"; 
}

template<> inline
const Char8 *FieldTraits<SamplerObjChunk *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSamplerObjChunkPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<SamplerObjChunk *,
                      RecordedRefCountPolicy, nsOSG  > SFRecSamplerObjChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<SamplerObjChunk *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecSamplerObjChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<SamplerObjChunk *,
                      WeakRefCountPolicy, nsOSG      > SFWeakSamplerObjChunkPtr;
/*! \ingroup GrpSystemStateFieldSFields */
typedef PointerSField<SamplerObjChunk *,
                      NoRefCountPolicy, nsOSG        > SFUncountedSamplerObjChunkPtr;


/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<SamplerObjChunk *,
                      RecordedRefCountPolicy, nsOSG  > MFRecSamplerObjChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<SamplerObjChunk *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecSamplerObjChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<SamplerObjChunk *,
                      WeakRefCountPolicy, nsOSG      > MFWeakSamplerObjChunkPtr;
/*! \ingroup GrpSystemStateFieldMFields */
typedef PointerMField<SamplerObjChunk *,
                      NoRefCountPolicy, nsOSG        > MFUncountedSamplerObjChunkPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFRecSamplerObjChunkPtr : 
    public PointerSField<SamplerObjChunk *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFUnrecSamplerObjChunkPtr : 
    public PointerSField<SamplerObjChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFWeakSamplerObjChunkPtr :
    public PointerSField<SamplerObjChunk *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldSFields \ingroup GrpLibOSGSystem */
struct SFUncountedSamplerObjChunkPtr :
    public PointerSField<SamplerObjChunk *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFRecSamplerObjChunkPtr :
    public PointerMField<SamplerObjChunk *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFUnrecSamplerObjChunkPtr :
    public PointerMField<SamplerObjChunk *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFWeakSamplerObjChunkPtr :
    public PointerMField<SamplerObjChunk *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpSystemStateFieldMFields \ingroup GrpLibOSGSystem */
struct MFUncountedSamplerObjChunkPtr :
    public PointerMField<SamplerObjChunk *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSAMPLEROBJCHUNKFIELDS_H_ */
