/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2013 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 * contact: dirk@opensg.org, gerrit.voss@vossg.org, carsten_neumann@gmx.net  *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGSSAOSTAGEFIELDS_H_
#define _OSGSSAOSTAGEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTechniquesDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE


class SSAOStage;

OSG_GEN_CONTAINERPTR(SSAOStage);
/*! \ingroup GrpContribTechniquesFieldTraits
    \ingroup GrpLibOSGContribTechniques
 */
template <>
struct FieldTraits<SSAOStage *, nsOSG> :
    public FieldTraitsFCPtrBase<SSAOStage *, nsOSG>
{
  private:

    static PointerType             _type;

  public:

    typedef FieldTraits<SSAOStage *, nsOSG>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTECHNIQUES_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

};

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSSAOStagePtr"; 
}

template<> inline
const Char8 *FieldTraits<SSAOStage *, nsOSG>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSSAOStagePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<SSAOStage *,
                      RecordedRefCountPolicy, nsOSG  > SFRecSSAOStagePtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<SSAOStage *,
                      UnrecordedRefCountPolicy, nsOSG> SFUnrecSSAOStagePtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<SSAOStage *,
                      WeakRefCountPolicy, nsOSG      > SFWeakSSAOStagePtr;
/*! \ingroup GrpContribTechniquesFieldSFields */
typedef PointerSField<SSAOStage *,
                      NoRefCountPolicy, nsOSG        > SFUncountedSSAOStagePtr;


/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<SSAOStage *,
                      RecordedRefCountPolicy, nsOSG  > MFRecSSAOStagePtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<SSAOStage *,
                      UnrecordedRefCountPolicy, nsOSG> MFUnrecSSAOStagePtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<SSAOStage *,
                      WeakRefCountPolicy, nsOSG      > MFWeakSSAOStagePtr;
/*! \ingroup GrpContribTechniquesFieldMFields */
typedef PointerMField<SSAOStage *,
                      NoRefCountPolicy, nsOSG        > MFUncountedSSAOStagePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFRecSSAOStagePtr : 
    public PointerSField<SSAOStage *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUnrecSSAOStagePtr : 
    public PointerSField<SSAOStage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFWeakSSAOStagePtr :
    public PointerSField<SSAOStage *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldSFields \ingroup GrpLibOSGContribTechniques */
struct SFUncountedSSAOStagePtr :
    public PointerSField<SSAOStage *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFRecSSAOStagePtr :
    public PointerMField<SSAOStage *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUnrecSSAOStagePtr :
    public PointerMField<SSAOStage *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFWeakSSAOStagePtr :
    public PointerMField<SSAOStage *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTechniquesFieldMFields \ingroup GrpLibOSGContribTechniques */
struct MFUncountedSSAOStagePtr :
    public PointerMField<SSAOStage *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGSSAOSTAGEFIELDS_H_ */
